In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd
import json
import plotly.express as px
import plotly.graph_objects as go
from utils.hilfsfunktionen import ( 
    select_dataframe, 
    find_relevant_years, 
    short_analysis_frame, 
    dump_json
)
from src.preparations import load_config
from src.analysis import create_dev_change_columns, create_indicator_frames
from src.paths import (
    EDUCATION_RAW,
    DEVELOPMENT_CONFIG,
    EDUCATION_CONFIG,
    EDUCATION_OUTPUT,
    DEVELOPMENT_OUTPUT,
    COUNTRY_INFO
)

df_edu_raw = pd.read_csv(EDUCATION_RAW, encoding="utf-8")

In [3]:
df_edu_raw.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.365540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"Adjusted net enrolment rate, primary, female (%)",SE.PRM.TENR.FE,43.351101,43.318150,44.640701,45.845718,46.449501,48.363892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Arab World,ARB,"Adjusted net enrolment rate, primary, gender p...",UIS.NERA.1.GPI,0.658570,0.656400,0.663290,0.672040,0.672610,0.691760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arab World,ARB,"Adjusted net enrolment rate, primary, male (%)",SE.PRM.TENR.MA,65.826233,65.993584,67.301857,68.219078,69.059013,69.914551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_edu_raw.shape

(886930, 70)

In [5]:
df_edu_raw.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.365540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"Adjusted net enrolment rate, primary, female (%)",SE.PRM.TENR.FE,43.351101,43.318150,44.640701,45.845718,46.449501,48.363892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Arab World,ARB,"Adjusted net enrolment rate, primary, gender p...",UIS.NERA.1.GPI,0.658570,0.656400,0.663290,0.672040,0.672610,0.691760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arab World,ARB,"Adjusted net enrolment rate, primary, male (%)",SE.PRM.TENR.MA,65.826233,65.993584,67.301857,68.219078,69.059013,69.914551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
indicators = list(df_edu_raw["Indicator Name"].unique())
indicators

['Adjusted net enrolment rate, lower secondary, both sexes (%)',
 'Adjusted net enrolment rate, lower secondary, female (%)',
 'Adjusted net enrolment rate, lower secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, lower secondary, male (%)',
 'Adjusted net enrolment rate, primary, both sexes (%)',
 'Adjusted net enrolment rate, primary, female (%)',
 'Adjusted net enrolment rate, primary, gender parity index (GPI)',
 'Adjusted net enrolment rate, primary, male (%)',
 'Adjusted net enrolment rate, upper secondary, both sexes (%)',
 'Adjusted net enrolment rate, upper secondary, female (%)',
 'Adjusted net enrolment rate, upper secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, upper secondary, male (%)',
 'Adjusted net intake rate to Grade 1 of primary education, both sexes (%)',
 'Adjusted net intake rate to Grade 1 of primary education, female (%)',
 'Adjusted net intake rate to Grade 1 of primary education, gender parity index (GPI)',
 'Adjusted net intake rate to Grade 1 of primary education, male (%)',
 'Adult illiterate population, 15+ years, % female',
 'Adult illiterate population, 15+ years, both sexes (number)',
 'Adult illiterate population, 15+ years, female (number)',
 'Adult illiterate population, 15+ years, male (number)',
 'Adult literacy rate, population 15+ years, both sexes (%)',
 'Adult literacy rate, population 15+ years, female (%)',
 'Adult literacy rate, population 15+ years, gender parity index (GPI)',
 'Adult literacy rate, population 15+ years, male (%)',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, female (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, female (number)',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, male',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, male (%)',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Top of scale',
 'Barro-Lee: Average years of primary schooling, age 15+, female',
 'Barro-Lee: Average years of primary schooling, age 15+, total',
 'Barro-Lee: Average years of primary schooling, age 15-19, female',
 'Barro-Lee: Average years of primary schooling, age 15-19, total',
 'Barro-Lee: Average years of primary schooling, age 20-24, female',
 'Barro-Lee: Average years of primary schooling, age 20-24, total',
 'Barro-Lee: Average years of primary schooling, age 25+, female',
 'Barro-Lee: Average years of primary schooling, age 25+, total',
 'Barro-Lee: Average years of primary schooling, age 25-29, female',
 'Barro-Lee: Average years of primary schooling, age 25-29, total',
 'Barro-Lee: Average years of primary schooling, age 30-34, female',
 'Barro-Lee: Average years of primary schooling, age 30-34, total',
 'Barro-Lee: Average years of primary schooling, age 35-39, female',
 'Barro-Lee: Average years of primary schooling, age 35-39, total',
 'Barro-Lee: Average years of primary schooling, age 40-44, female',
 'Barro-Lee: Average years of primary schooling, age 40-44, total',
 'Barro-Lee: Average years of primary schooling, age 45-49, female',
 'Barro-Lee: Average years of primary schooling, age 45-49, total',
 'Barro-Lee: Average years of primary schooling, age 50-54, female',
 'Barro-Lee: Average years of primary schooling, age 50-54, total',
 'Barro-Lee: Average years of primary schooling, age 55-59, female',
 'Barro-Lee: Average years of primary schooling, age 55-59, total',
 'Barro-Lee: Average years of primary schooling, age 60-64, female',
 'Barro-Lee: Average years of primary schooling, age 60-64, total',
 'Barro-Lee: Average years of primary schooling, age 65-69, female',
 'Barro-Lee: Average years of primary schooling, age 65-69, total',
 'Barro-Lee: Average years of primary schooling, age 70-74, female',
 'Barro-Lee: Average years of primary schooling, age 70-74, total',
 'Barro-Lee: Average years of primary schooling, age 75+, female',
 'Barro-Lee: Average years of primary schooling, age 75+, total',
 'Barro-Lee: Average years of secondary schooling, age 15+, female',
 'Barro-Lee: Average years of secondary schooling, age 15+, total',
 'Barro-Lee: Average years of secondary schooling, age 15-19, female',
 'Barro-Lee: Average years of secondary schooling, age 15-19, total',
 'Barro-Lee: Average years of secondary schooling, age 20-24, female',
 'Barro-Lee: Average years of secondary schooling, age 20-24, total',
 'Barro-Lee: Average years of secondary schooling, age 25+, female',
 'Barro-Lee: Average years of secondary schooling, age 25+, total',
 'Barro-Lee: Average years of secondary schooling, age 25-29, female',
 'Barro-Lee: Average years of secondary schooling, age 25-29, total',
 'Barro-Lee: Average years of secondary schooling, age 30-34, female',
 'Barro-Lee: Average years of secondary schooling, age 30-34, total',
 'Barro-Lee: Average years of secondary schooling, age 35-39, female',
 'Barro-Lee: Average years of secondary schooling, age 35-39, total',
 'Barro-Lee: Average years of secondary schooling, age 40-44, female',
 'Barro-Lee: Average years of secondary schooling, age 40-44, total',
 'Barro-Lee: Average years of secondary schooling, age 45-49, female',
 'Barro-Lee: Average years of secondary schooling, age 45-49, total',
 'Barro-Lee: Average years of secondary schooling, age 50-54, female',
 'Barro-Lee: Average years of secondary schooling, age 50-54, total',
 'Barro-Lee: Average years of secondary schooling, age 55-59, female',
 'Barro-Lee: Average years of secondary schooling, age 55-59, total',
 'Barro-Lee: Average years of secondary schooling, age 60-64, female',
 'Barro-Lee: Average years of secondary schooling, age 60-64, total',
 'Barro-Lee: Average years of secondary schooling, age 65-69, female',
 'Barro-Lee: Average years of secondary schooling, age 65-69, total',
 'Barro-Lee: Average years of secondary schooling, age 70-74, female',
 'Barro-Lee: Average years of secondary schooling, age 70-74, total',
 'Barro-Lee: Average years of secondary schooling, age 75+, female',
 'Barro-Lee: Average years of secondary schooling, age 75+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15+, female',
 'Barro-Lee: Average years of tertiary schooling, age 15+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, female',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, total',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, female',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, total',
 'Barro-Lee: Average years of tertiary schooling, age 25+, female',
 'Barro-Lee: Average years of tertiary schooling, age 25+, total',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, female',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, total',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, female',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, total',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, female',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, total',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, female',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, total',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, female',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, total',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, female',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, total',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, female',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, total',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, female',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, total',

In [7]:
indicators_group = []
for ind in indicators:
    parts = ind.split(",")
    first_part = parts[0]
    if first_part not in indicators_group:
        indicators_group.append(first_part)

indicators_group

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education',
 'Africa Dataset: Teacher attrition rate from public primary education',
 'Africa Dataset: Teacher attrition rate from public upper secondary education',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Top of scale',
 'Barro-Lee: Average years of primary schooling',
 'Barro-Lee: Average years of secondary schooling',
 'Barro-Lee: Average years of tertiary schooling',
 'Barro-Lee: Average years of total schooling',
 'Barro-Lee: Percentage of female population age 15+ with no education',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 15-19 with no education',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 20-24 with no education',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 25+ with no education',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 25-29 with no education',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 30-34 with no education',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 35-39 with no education',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 40-44 with no education',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 45-49 with no education',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 50-54 with no education',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 55-59 with no education',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 60-64 with no education',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 65-69 with no education',
 'Barro-Lee: Percentage of female population age 65-69 with primary schooling. Completed Primary',

In [8]:
indicators_group2 = []
for ind in indicators_group:
    parts = ind.split(".")
    first_part = parts[0]
    if first_part not in indicators_group2:
        indicators_group2.append(first_part)

indicators_group2

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education',
 'Africa Dataset: Teacher attrition rate from public primary education',
 'Africa Dataset: Teacher attrition rate from public upper secondary education',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD',
 'Barro-Lee: Average years of primary schooling',
 'Barro-Lee: Average years of secondary schooling',
 'Barro-Lee: Average years of tertiary schooling',
 'Barro-Lee: Average years of total schooling',
 'Barro-Lee: Percentage of female population age 15+ with no education',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with no education',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with no education',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 25+ with no education',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with no education',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with no education',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with no education',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with no education',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with no education',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with no education',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with no education',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with no education',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with no education',
 'Barro-Lee: Percentage of female population age 65-69 with primary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with secondary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with no education',
 'Barro-Lee: Percentage of female population age 70-74 with primary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with secondary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 75+ with no education',
 'Barro-Lee: Percentage of female population age 75+ with primary schooling',
 'Barro-Lee: Percentage of female population age 75+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 75+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 15+ with no education',
 'Barro-Lee: Percentage of population age 15+ with primary schooling',
 'Barro-Lee: Percentage of population age 15+ with secondary schooling',
 'Barro-Lee: Percentage of population age 15+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 15-19 with no education',
 'Barro-Lee: Percentage of population age 15-19 with primary schooling',
 'Barro-Lee: Percentage of population age 15-19 with secondary schooling',
 'Barro-Lee: Percentage of population age 15-19 with tertiary schooling',
 'Barro-Lee: Percentage of population age 20-24 with no education',
 'Barro-Lee: Percentage of population age 20-24 with primary schooling',
 'Barro-Lee: Percentage of population age 20-24 with secondary schooling',
 'Barro-Lee: Percentage of population age 20-24 with tertiary schooling',
 'Barro-Lee: Percentage of population age 25+ with no education',
 'Barro-Lee: Percentage of population age 25+ with primary schooling',
 'Barro-Lee: Percentage of population age 25+ with secondary schooling',
 'Barro-Lee: Percentage of population age 25+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 25-29 with no education',
 'Barro-Lee: Percentage of population age 25-29 with primary schooling',
 'Barro-Lee: Percentage of population age 25-29 with secondary schooling',
 'Barro-Lee: Percentage of population age 25-29 with tertiary schooling',
 'Barro-Lee: Percentage of population age 30-34 with no education',
 'Barro-Lee: Percentage of population age 30-34 with primary schooling',
 'Barro-Lee: Percentage of population age 30-34 with secondary schooling',
 'Barro-Lee: Percentage of population age 30-34 with tertiary schooling',
 'Barro-Lee: Percentage of population age 35-39 with no education',
 'Barro-Lee: Percentage of population age 35-39 with primary schooling',
 'Barro-Lee: Percentage of population age 35-39 with secondary schooling',
 'Barro-Lee: Percentage of population age 35-39 with tertiary schooling',
 'Barro-Lee: Percentage of population age 40-44 with no education',
 'Barro-Lee: Percentage of population age 40-44 with primary schooling',
 'Barro-Lee: Percentage of population age 40-44 with secondary schooling',
 'Barro-Lee: Percentage of population age 40-44 with tertiary schooling',
 'Barro-Lee: Percentage of population age 45-49 with no education',
 'Barro-Lee: Percentage of population age 45-49 with primary schooling',
 'Barro-Lee: Percentage of population age 45-49 with secondary schooling',
 'Barro-Lee: Percentage of population age 45-49 with tertiary schooling',
 'Barro-Lee: Percentage of population age 50-54 with no education',
 'Barro-Lee: Percentage of population age 50-54 with primary schooling',
 'Barro-Lee: Percentage of population age 50-54 with secondary schooling',
 'Barro-Lee: Percentage of population age 50-54 with tertiary schooling',
 'Barro-Lee: Percentage of population age 55-59 with no education',
 'Barro-Lee: Percentage of population age 55-59 with primary schooling',
 'Barro-Lee: Percentage of population age 55-59 with secondary schooling',
 'Barro-Lee: Percentage of population age 55-59 with tertiary schooling',
 'Barro-Lee: Percentage of population age 60-64 with no education',
 'Barro-Lee: Percentage of population age 60-64 with primary schooling',
 'Barro-Lee: Percentage of population age 60-64 with secondary schooling',
 'Barro-Lee: Percentage of population age 60-64 with tertiary schooling',
 'Barro-Lee: Percentage of population age 65-69 with no education',
 'Barro-Lee: Percentage of population age 65-69 with primary schooling',
 'Barro-Lee: Percentage of population age 65-69 with secondary schooling',
 'Barro-Lee: Percentage of population age 65-69 with tertiary schooling',
 'Barro-Lee: Percentage of population age 70-74 with no education',
 'Barro-Lee: Percentage of population age 70-74 with primary schooling',
 'Barro-Lee: Percentage of population age 70-74 with secondary schooling',
 'Barro-Lee: Percentage of population age 70-74 with tertiary schooling',
 'Barro-Lee: Percentage of population age 75+ with no education',
 'Barro-Lee: Percentage of population age 75+ with primary schooling',
 'Barro-Lee: Percentage of population age 75+ with secondary schooling',
 'Barro-Lee: Percentage of population age 75+ with tertiary schooling',
 'Barro-Lee: Population in thousands',
 'Capital expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Capital expenditure as % of total expenditure in primary public institutions (%)',
 'Capital expenditure as % of total expenditure in public institutions (%)',
 'Capital expenditure as % of total expenditure in secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Cumulative drop-out rate to the last grade of lower secondary general education',
 'Cumulative drop-out rate to the last grade of primary education',
 'Current expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure as % of total expenditure in primary public institutions (%)',
 'Current expenditure as % of total expenditure in public institutions (%)',
 'Current expenditure as % of total expenditure in secondary public institutions (%)',
 'Current expenditure as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in upper-secondary public institutions (%)',

In [9]:
indicators_group3 = []
for ind in indicators_group2:
    parts = ind.split(":")
    first_part = parts[0]
    if first_part not in indicators_group3:
        indicators_group3.append(first_part)

indicators_group3

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD',
 'Barro-Lee',
 'Capital expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Capital expenditure as % of total expenditure in primary public institutions (%)',
 'Capital expenditure as % of total expenditure in public institutions (%)',
 'Capital expenditure as % of total expenditure in secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Cumulative drop-out rate to the last grade of lower secondary general education',
 'Cumulative drop-out rate to the last grade of primary education',
 'Current expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure as % of total expenditure in primary public institutions (%)',
 'Current expenditure as % of total expenditure in public institutions (%)',
 'Current expenditure as % of total expenditure in secondary public institutions (%)',
 'Current expenditure as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in primary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'DHS',
 'Drop-out rate from Grade 1 of lower secondary general education',
 'Drop-out rate from Grade 1 of primary education',
 'Drop-out rate from Grade 2 of lower secondary general education',
 'Drop-out rate from Grade 2 of primary education',
 'Drop-out rate from Grade 3 of lower secondary general education',
 'Drop-out rate from Grade 3 of primary education',
 'Drop-out rate from Grade 4 of lower secondary general education',
 'Drop-out rate from Grade 4 of primary education',
 'Drop-out rate from Grade 5 of lower secondary general education',
 'Drop-out rate from Grade 5 of primary education',
 'Drop-out rate from Grade 6 of primary education',
 'Duration of compulsory education (years)',
 'Early school leavers from primary education',
 'Effective transition rate from primary to lower secondary general education',
 'EGRA',
 'Elderly illiterate population',
 'Elderly literacy rate',
 'Enrolment in early childhood education',
 'Enrolment in early childhood educational development programmes',
 'Enrolment in Grade 1 of lower secondary general education',
 'Enrolment in Grade 1 of primary education',
 'Enrolment in Grade 2 of lower secondary general education',
 'Enrolment in Grade 2 of primary education',
 'Enrolment in Grade 3 of lower secondary general education',
 'Enrolment in Grade 3 of primary education',
 'Enrolment in Grade 4 of lower secondary general education',
 'Enrolment in Grade 4 of primary education',
 'Enrolment in Grade 5 of lower secondary general education',
 'Enrolment in Grade 5 of primary education',
 'Enrolment in Grade 6 of lower secondary general education',
 'Enrolment in Grade 6 of primary education',
 'Enrolment in Grade 7 of primary education',
 'Enrolment in lower secondary education',
 'Enrolment in lower secondary general education',
 'Enrolment in lower secondary general',
 'Enrolment in lower secondary vocational',
 'Enrolment in post-secondary non-tertiary education',
 'Enrolment in pre-primary education',
 'Enrolment in primary education',
 'Enrolment in secondary education',
 'Enrolment in secondary general',
 'Enrolment in secondary vocational',
 'Enrolment in tertiary education per 100',
 'Enrolment in tertiary education',
 'Enrolment in upper secondary education',
 'Enrolment in upper secondary general',
 'Enrolment in upper secondary vocational',
 'Expenditure on education as % of total government expenditure (%)',
 'Expenditure on education not allocated by level as % of government expenditure on education (%)',
 'Expenditure on lower secondary as % of government expenditure on education (%)',
 'Expenditure on lower secondary as % of total government expenditure (%)',
 'Expenditure on post-secondary non-tertiary as % of government expenditure on education (%)',
 'Expenditure on post-secondary non-tertiary as % of total government expenditure (%)',
 'Expenditure on pre-primary as % of government expenditure on education (%)',
 'Expenditure on pre-primary as % of total government expenditure (%)',
 'Expenditure on primary as % of government expenditure on education (%)',
 'Expenditure on primary as % of total government expenditure (%)',
 'Expenditure on secondary and post-secondary non-tertiary vocational as % of government expenditure on education (%)',
 'Expenditure on secondary and post-secondary non-tertiary vocational education as % of total government expenditure (%)',
 'Expenditure on secondary as % of government expenditure on education (%)',
 'Expenditure on secondary as % of total government expenditure (%)',
 'Expenditure on tertiary as % of government expenditure on education (%)',
 'Expenditure on tertiary as % of total government expenditure (%)',
 'Expenditure on upper secondary as % of government expenditure on education (%)',
 'Expenditure on upper secondary as % of total government expenditure (%)',
 'GDP at market prices (constant 2005 US$)',
 'GDP at market prices (current US$)',
 'GDP per capita (constant 2005 US$)',
 'GDP per capita (current US$)',
 'GDP per capita',
 'GDP',
 'GNI (current US$)',
 'GNI per capita',
 'GNI',
 'Government expenditure in educational institutions as % of GDP (%)',
 'Government expenditure in post-secondary non-tertiary institutions as % of GDP (%)',
 'Government expenditure in pre-primary institutions as % of GDP (%)',
 'Government expenditure in primary institutions as % of GDP (%)',
 'Government expenditure in secondary institutions education as % of GDP (%)',
 'Government expenditure in tertiary institutions as % of GDP (%)',
 'Government expenditure on education as % of GDP (%)',
 'Government expenditure on post-secondary non-tertiary education as % of GDP (%)',
 'Government expenditure on pre-primary education as % of GDP (%)',
 'Government expenditure on primary education as % of GDP (%)',
 'Government expenditure on secondary and post-secondary non-tertiary vocational education as % of GDP (%)',
 'Government expenditure on secondary education as % of GDP (%)',
 'Government expenditure on tertiary education as % of GDP (%)',
 'Government expenditure per lower secondary student (constant PPP$)',
 'Government expenditure per lower secondary student (constant US$)',
 'Government expenditure per lower secondary student (PPP$)',
 'Government expenditure per lower secondary student (US$)',
 'Government expenditure per lower secondary student as % of GDP per capita (%)',
 'Government expenditure per post-secondary non-tertiary student (constant PPP$)',
 'Government expenditure per post-secondary non-tertiary student (constant US$)',
 'Government expenditure per post-secondary non-tertiary student (PPP$)',
 'Government expenditure per post-secondary non-tertiary student (US$)',
 'Government expenditure per post-secondary non-tertiary student as % of GDP per capita (%)',
 'Government expenditure per primary student (constant PPP$)',
 'Government expenditure per primary student (constant US$)',
 'Government expenditure per primary student (PPP$)',
 'Government expenditure per primary student (US$)',
 'Government expenditure per primary student as % of GDP per capita (%)',
 'Government expenditure per secondary student (constant PPP$)',
 'Government expenditure per secondary student (constant US$)',
 'Government expenditure per secondary student (PPP$)',
 'Government expenditure per secondary student (US$)',
 'Government expenditure per secondary student as % of GDP per capita (%)',
 'Government expenditure per tertiary student (constant PPP$)',
 'Government expenditure per tertiary student (constant US$)',
 'Government expenditure per tertiary student (PPP$)',
 'Government expenditure per tertiary student (US$)',
 'Government expenditure per tertiary student as % of GDP per capita (%)',
 'Government expenditure per upper secondary student (constant PPP$)',
 'Government expenditure per upper secondary student (constant US$)',
 'Government expenditure per upper secondary student (PPP$)',
 'Government expenditure per upper secondary student (US$)',
 'Government expenditure per upper secondary student as % of GDP per capita (%)',
 'Graduates from ISCED 5 programmes in tertiary education',
 'Graduates from ISCED 6 programmes in tertiary education',
 'Graduates from ISCED 7 programmes in tertiary education',
 'Graduates from ISCED 8 programmes in tertiary education',
 'Graduates from tertiary education',
 'Gross enrolment ratio',
 'Gross graduation ratio from first degree programmes (ISCED 6 and 7) in tertiary education',
 'Gross graduation ratio from lower secondary education',
 'Gross graduation ratio from primary education',
 'Gross intake ratio to Grade 1 of lower secondary general education',
 'Gross intake ratio to Grade 1 of primary education',
 'Gross outbound enrolment ratio',
 'Illiterate population',
 'Inbound mobility rate',
 'Internet users (per 100 people)',
 'Labor force with advanced education (% of total)',
 'Labor force with advanced education',
 'Labor force with basic education (% of total)',
 'Labor force with basic education',
 'Labor force with intermediate education (% of total)',
 'Labor force with intermediate education',
 'Labor force',
 'Literacy rate',
 'LLECE',
 'Lower secondary completion rate',
 'MICS',
 'Mortality rate',
 'Net enrolment rate',
 'Net flow of internationally mobile students (inbound - outbound)',
 'Net flow ratio of internationally mobile students (inbound - outbound)',
 'Net intake rate to Grade 1 of primary education by over-age entrants (+1 year)',
 'Net intake rate to Grade 1 of primary education by under-age entrants (-1 year)',
 'Net intake rate to Grade 1 of primary education',
 'New entrants to Grade 1 of primary education with early childhood education experience ',
 'New entrants to Grade 1 of primary education with early childhood education experience',
 'New entrants to Grade 1 of primary education',
 'Official entrance age to compulsory education (years)',
 'Official entrance age to lower secondary education (years)',
 'Official entrance age to post-secondary non-tertiary education (years)',
 'Official entrance age to pre-primary education (years)',
 'Official entrance age to primary education (years)',
 'Official entrance age to upper secondary education (years)',
 'Outbound mobility ratio',
 'Out-of-school adolescents of lower secondary school age',
 'Out-of-school children of primary school age in pre-primary education',
 'Out-of-school children of primary school age',
 'Out-of-school youth of upper secondary school age',
 'Over-age enrolment ratio in primary education',
 'PASEC',
 'Percentage of all inbound internationally mobile students in tertiary education in the host country who are female',
 'Percentage of all students in tertiary education enrolled in ISCED 5',
 'Percentage of all students in tertiary education enrolled in ISCED 6',
 'Percentage of all students in tertiary education enrolled in ISCED 7',
 'Percentage of all students in tertiary education enrolled in ISCED 8',
 'Percentage of enrolment in early childhood education programmes in private institutions (%)',
 'Percentage of enrolment in early childhood educational development programmes in private institutions (%)',
 'Percentage of enrolment in lower secondary education in private institutions (%)',
 'Percentage of enrolment in post-secondary non-tertiary education in private institutions (%)',
 'Percentage of enrolment in pre-primary education in private institutions (%)',
 'Percentage of enrolment in primary education in private institutions (%)',
 'Percentage of enrolment in secondary education in private institutions (%)',
 'Percentage of enrolment in tertiary education in private institutions (%)',
 'Percentage of enrolment in upper secondary education in private institutions (%)',
 'Percentage of female graduates from tertiary education graduating from Agriculture programmes',
 'Percentage of female graduates from tertiary education graduating from Education programmes',
 'Percentage of female graduates from tertiary education graduating from Engineering',
 'Percentage of female graduates from tertiary education graduating from Health and Welfare programmes',
 'Percentage of female graduates from tertiary education graduating from Humanities and Arts programmes',
 'Percentage of female graduates from tertiary education graduating from programmes in unspecified fields',
 'Percentage of female graduates from tertiary education graduating from Science programmes',
 'Percentage of female graduates from tertiary education graduating from Services programmes',
 'Percentage of female graduates from tertiary education graduating from Social Sciences',
 'Percentage of female students enrolled in primary education who are over-age',
 'Percentage of female students enrolled in primary education who are under-age',
 'Percentage of female students in lower secondary education enrolled in general programmes',
 'Percentage of female students in lower secondary education enrolled in vocational programmes',
 'Percentage of female students in post-secondary non-tertiary education enrolled in general programmes',
 'Percentage of female students in post-secondary non-tertiary education enrolled in vocational programmes',
 'Percentage of female students in secondary education enrolled in general programmes',
 'Percentage of female students in secondary education enrolled in vocational programmes',
 'Percentage of female students in tertiary education enrolled in Agriculture programmes',
 'Percentage of female students in tertiary education enrolled in Education programmes',
 'Percentage of female students in tertiary education enrolled in Engineering',
 'Percentage of female students in tertiary education enrolled in Health and Welfare programmes',
 'Percentage of female students in tertiary education enrolled in Humanities and Arts programmes',
 'Percentage of female students in tertiary education enrolled in ISCED 5',
 'Percentage of female students in tertiary education enrolled in ISCED 6',
 'Percentage of female students in tertiary education enrolled in ISCED 7',
 'Percentage of female students in tertiary education enrolled in ISCED 8',
 'Percentage of female students in tertiary education enrolled in programmes in unspecified fields',
 'Percentage of female students in tertiary education enrolled in Science programmes',
 'Percentage of female students in tertiary education enrolled in Services programmes',
 'Percentage of female students in tertiary education enrolled in Social Sciences',
 'Percentage of female students in upper secondary education enrolled in general programmes',
 'Percentage of female students in upper secondary education enrolled in vocational programmes',
 'Percentage of female teachers in lower secondary education who are trained',
 'Percentage of female teachers in post-secondary non-tertiary education who are trained',
 'Percentage of female teachers in pre-primary education who are trained',
 'Percentage of female teachers in primary education who are trained',
 'Percentage of female teachers in secondary education who are trained',
 'Percentage of female teachers in upper secondary education who are trained',
 'Percentage of graduates from Agriculture programmes in tertiary education who are female (%)',
 'Percentage of graduates from Education programmes in tertiary education who are female (%)',
 'Percentage of graduates from Engineering',
 'Percentage of graduates from Health and Welfare programmes in tertiary education who are female (%)',
 'Percentage of graduates from Humanities and Arts programmes in tertiary education who are female (%)',
 'Percentage of graduates from non-science and non-technology fields in tertiary education who are female (%)',
 'Percentage of graduates from programmes in unspecified fields in tertiary education who are female (%)',
 'Percentage of graduates from Science and Technology programmes in tertiary education who are female (%)',
 'Percentage of graduates from Science programmes in tertiary education who are female (%)',
 'Percentage of graduates from Services programmes in tertiary education who are female (%)',
 'Percentage of graduates from Social Sciences',
 'Percentage of graduates from tertiary education graduating from Agriculture programmes',
 'Percentage of graduates from tertiary education graduating from Education programmes',
 'Percentage of graduates from tertiary education graduating from Engineering',
 'Percentage of graduates from tertiary education graduating from Health and Welfare programmes',
 'Percentage of graduates from tertiary education graduating from Humanities and Arts programmes',
 'Percentage of graduates from tertiary education graduating from programmes in unspecified fields',
 'Percentage of graduates from tertiary education graduating from Science programmes',
 'Percentage of graduates from tertiary education graduating from Services programmes',
 'Percentage of graduates from tertiary education graduating from Social Sciences',
 'Percentage of graduates from tertiary education who are female (%)',
 'Percentage of graduates from tertiary ISCED 5 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 6 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 7 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 8 programmes who are female (%)',
 'Percentage of male graduates from tertiary education graduating from Agriculture programmes',

## Erste Übersicht bzgl. Datenqualität und -struktur

In [10]:
short_analysis_frame(df_edu_raw)

========== DataFrame Qualität ==========


Anzahl Zeilen: 886930
davon: 0 Duplikate

Anzahl Spalten: 70
davon:
    66 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
Country Name        str            0.00               242
Country Code        str            0.00               242
Indicator Name      str            0.00              3665
Indicator Code      str            0.00              3665
1970            float64           91.85             24595
...                 ...             ...               ...
2085            float64           94.20              7335
2090            float64           94.20              7150
2095            float64           94.20              7044
2100            float64           94.20              6914
Unnamed: 69     float64          100.00                 0

[70 rows x 3 columns]

## Entwicklung einer Funktion zum Auffinden für den Indikator relevanter Jahre

In [11]:
EDU_INDICATOR_CODE = "LO.TIMSS.SCI8"
DEV_INDICATOR_CODE = "NY.GDP.PCAP.KD"
TIMSS_YEARS_LIST = ["1999", "2003", "2007", "2011", "2015", "2019", "2023"]

filter_timss = df_edu_raw["Indicator Code"] == EDU_INDICATOR_CODE
df_indicator = df_edu_raw[filter_timss]
records_total = df_indicator.shape[0]

col_list = df_indicator.columns

year_cols = []

for col in col_list:
    if col.isdigit():
        year_cols.append(col)

year_cols_relevant = []

for col in year_cols:
    values_count = df_indicator[col].notna().sum()
    if values_count > 0:
        year_cols_relevant.append(col)

year_cols_relevant

['1995', '1999', '2003', '2007', '2011', '2015']

In [12]:
years = find_relevant_years(df_indicator)
years

['1995', '1999', '2003', '2007', '2011', '2015']

## Extrahieren relevanter Bildungsdaten

- die internationalen Bildungsdaten werden auf den relevanten TIMSS-Score (Science) gefiltert
- danach wird nur auf Score-relevante Jahre gefiltert

In [13]:
df_base = select_dataframe("edu")

df_timss_science, df_timss_science_long = create_indicator_frames(frame_name="edu", indicator_code=EDU_INDICATOR_CODE, indicator_title="timss_science")

df_timss_science

,country_name,country_code,indicator_name,indicator_code,timss_science_data_count,1995,1999,2003,2007,2011,2015
85,Algeria,DZA,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,1,NaN,NaN,NaN,408.059523,NaN,NaN
230,Armenia,ARM,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,3,NaN,NaN,461.266680,487.960381,436.924652,NaN
296,Australia,AUS,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,6,514.000000,540.258156,527.000000,515.000000,519.000000,512.0
335,Austria,AUT,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,1,538.933284,NaN,NaN,NaN,NaN,NaN
415,Bahrain,BHR,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,4,NaN,NaN,438.000000,467.000000,452.000000,466.0
...,...,...,...,...,...,...,...,...,...,...,...
5573,Turkey,TUR,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,4,NaN,432.950957,NaN,454.158975,483.000000,493.0
5672,Ukraine,UKR,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,2,NaN,NaN,NaN,485.062954,500.991769,NaN
5706,United Arab Emirates,ARE,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,2,NaN,NaN,NaN,NaN,465.000000,477.0
5777,United States,USA,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,6,513.000000,515.000000,527.000000,520.000000,525.000000,530.0
5958,West Bank and Gaza,PSE,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,3,NaN,NaN,435.386769,404.126171,420.454965,NaN

## Nutzbar machen der Scoredaten
- der DataFrame wird ins Long-Format gebracht. 
- Zeilen ohne Score werden direkt als irrelevant entfernt

In [14]:
df_timss_science_long.columns = (
        df_timss_science_long.columns
        .str.replace("_", " ")
        .str.title()
    )

years = find_relevant_years(df_timss_science)

for year in years:
    df_year = df_timss_science_long[df_timss_science_long["Year"] == int(year)]
    
    fig = px.bar(
        df_year.sort_values("Timss Science Score").tail(10),
        x="Timss Science Score",
        y="Country Name",
        title=f"TIMSS Science: Top 20 Countries ({year})",
    )
    # fig.show()

## Datenstruktur der zwei neu erzeugten Tabellen

In [15]:
df_edu = pd.read_csv(EDUCATION_OUTPUT, encoding="utf-8")
df_dev = pd.read_csv(DEVELOPMENT_OUTPUT, encoding="utf-8")

short_analysis_frame(df_edu)

========== DataFrame Qualität ==========


Anzahl Zeilen: 6029
davon: 0 Duplikate

Anzahl Spalten: 51
davon:
    47 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
country_name        str            0.00               209
country_code        str            0.00               209
indicator_name      str            0.00                46
indicator_code      str            0.00                46
1970            float64           93.91               362
1971            float64           79.37              1226
1972            float64           80.94              1142
1973            float64           80.74              1157
1974            float64           81.19              1133
1975            float64           80.94              1146
1976            float64           79.90              1206
1977            float64           80.10              1196
1978            float64           80.18              1191
1979            float64           79.76              1216
1980            float64           78.90              1269
1981            float64           77.13              1374
1982            float64           79.27              1245
1983            float64           79.27              1245
1984            float64           78.45              1297
1985            float64           79.45              1237
1986            float64           77.43              1355
1987            float64           79.42              1239
1988            float64           79.95              1206
1989            float64           79.47              1237
1990            float64           79.12              1257
1991            float64           78.24              1306
1992            float64           78.74              1280
1993            float64           78.59              1290
1994            float64           78.07              1320
1995            float64           76.33              1407
1996            float64           79.35              1244
1997            float64           83.63               987
1998            float64           77.61              1348
1999            float64           56.89              2560
2000            float64           55.23              2680
2001            float64           56.91              2580
2002            float64           55.38              2679
2003            float64           52.36              2809
2004            float64           54.29              2736
2005            float64           54.87              2707
2006            float64           53.03              2818
2007            float64           50.74              2899
2008            float64           52.70              2831
2009            float64           47.35              3156
2010            float64           49.98              2997
2011            float64           45.78              3190
2012            float64           46.13              3226
2013            float64           51.55              2901
2014            float64           55.58              2647
2015            float64           67.91              1851
2016            float64           97.98               120

In [16]:
short_analysis_frame(df_dev)

========== DataFrame Qualität ==========


Anzahl Zeilen: 4951
davon: 0 Duplikate

Anzahl Spalten: 30
davon:
    26 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
country_name        str            0.00               214
country_code        str            0.00               214
indicator_name      str            0.00                26
indicator_code      str            0.00                26
1999            float64           35.93              2680
2000            float64           26.56              3108
2001            float64           33.91              2808
2002            float64           24.92              3197
2003            float64           24.92              3173
2004            float64           21.33              3330
2005            float64           21.47              3324
2006            float64           18.58              3459
2007            float64           16.60              3545
2008            float64           14.62              3626
2009            float64           13.84              3646
2010            float64           13.01              3649
2011            float64           13.09              3650
2012            float64           12.36              3737
2013            float64           12.44              3724
2014            float64           11.65              3760
2015            float64           11.17              3775
2016            float64           10.99              3783
2017            float64           10.60              3824
2018            float64           10.22              3811
2019            float64           11.07              3803
2020            float64           11.96              3779
2021            float64           12.58              3718
2022            float64           18.36              3545
2023            float64           23.35              3360
2024            float64           38.21              2743

In [17]:
df_dev

,country_name,country_code,indicator_name,indicator_code,1999,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.420817,14.342153,18.380042,16.235278,15.702752
1,Afghanistan,AFG,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,308.318270,277.118051,338.139974,346.071627,338.637274,...,565.569730,563.872337,562.769574,553.125152,557.861533,527.834554,408.625855,377.665627,378.066303,374.376696
2,Afghanistan,AFG,Government Effectiveness - Governance estimate...,GOV_WGI_GE_EST,NaN,-2.344602,NaN,-2.098876,-2.108121,-1.156126,...,-1.471172,-1.417730,-1.442187,-1.631250,-1.654080,-1.716728,-1.705904,-1.964611,-2.092459,-1.933997
3,Afghanistan,AFG,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.289077,37.069564,54.505427,50.764300,68.060273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,Zimbabwe,ZWE,"Prevalence of HIV, total (% of population ages...",SH.DYN.AIDS.ZS,27.000000,25.800000,24.500000,23.200000,21.900000,20.600000,...,14.500000,14.100000,13.600000,13.100000,12.500000,12.000000,11.500000,10.900000,10.300000,9.800000
4947,Zimbabwe,ZWE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,64.400000,69.500000,72.300000,74.700000,78.000000,81.800000,...,80.800000,81.700000,82.000000,79.700000,81.000000,84.100000,82.400000,NaN,NaN,NaN
4948,Zimbabwe,ZWE,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.PC.CE.AR5,2.919746,2.627267,2.623309,2.373381,2.079466,1.989973,...,1.977177,1.821388,1.758746,1.864458,1.733276,1.596830,1.718639,1.744073,1.843543,1.850644
4949,Zimbabwe,ZWE,"Trademark applications, resident, by count",IP.TMK.RSCT,NaN,NaN,NaN,NaN,NaN,NaN,...,285.000000,155.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4950,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,6.000000,5.685000,5.313000,5.005000,4.738000,4.390000,...,5.399000,5.896000,6.350000,6.788000,7.373000,8.617000,9.540000,10.087000,9.348000,9.435000

In [18]:
df_timss, df_timss_long = create_indicator_frames(indicator_code=EDU_INDICATOR_CODE, frame_name="edu", indicator_title="timss_science")
df_gdp_per_capita, df_gdp_per_capita_long = create_indicator_frames(indicator_code=DEV_INDICATOR_CODE, frame_name="dev", indicator_title="gdp_per_capita")

df_timss.head(10)

,country_name,country_code,indicator_name,indicator_code,timss_science_data_count,1995,1999,2003,2007,2011,2015
85,Algeria,DZA,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,1,NaN,NaN,NaN,408.059523,NaN,NaN
230,Armenia,ARM,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,3,NaN,NaN,461.266680,487.960381,436.924652,NaN
296,Australia,AUS,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,6,514.000000,540.258156,527.000000,515.000000,519.000000,512.0
335,Austria,AUT,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,1,538.933284,NaN,NaN,NaN,NaN,NaN
415,Bahrain,BHR,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,4,NaN,NaN,438.000000,467.000000,452.000000,466.0
701,Bosnia and Herzegovina,BIH,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,1,NaN,NaN,NaN,465.745173,NaN,NaN
739,Botswana,BWA,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,2,NaN,NaN,364.569248,354.534086,NaN,NaN
844,Bulgaria,BGR,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,3,NaN,518.010990,478.843142,470.283975,NaN,NaN
1029,Canada,CAN,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,3,513.987704,533.081997,NaN,NaN,NaN,526.0
1131,Chile,CHL,TIMSS: Mean performance on the science scale f...,LO.TIMSS.SCI8,4,NaN,420.000000,413.000000,NaN,461.000000,454.0

In [19]:
short_analysis_frame(df_gdp_per_capita)

========== DataFrame Qualität ==========


Anzahl Zeilen: 212
davon: 0 Duplikate

Anzahl Spalten: 31
davon:
    27 numerisch
    0 datetime
    4 string/object
    0 kategorial

                          Datentyp  Fehlende Werte  Eindeutige Werte
country_name                   str            0.00               212
country_code                   str            0.00               212
indicator_name                 str            0.00                 1
indicator_code                 str            0.00                 1
gdp_per_capita_data_count    int64            0.00                14
1999                       float64            7.55               196
2000                       float64            6.60               198
2001                       float64            6.60               198
2002                       float64            4.72               202
2003                       float64            4.72               202
2004                       float64            4.72               202
2005                       float64            4.72               202
2006                       float64            4.25               203
2007                       float64            3.77               204
2008                       float64            2.36               207
2009                       float64            1.42               209
2010                       float64            1.42               209
2011                       float64            1.42               209
2012                       float64            1.89               208
2013                       float64            1.42               209
2014                       float64            1.42               209
2015                       float64            0.47               211
2016                       float64            1.89               208
2017                       float64            1.89               208
2018                       float64            1.89               208
2019                       float64            2.36               207
2020                       float64            2.36               207
2021                       float64            2.36               207
2022                       float64            2.36               207
2023                       float64            4.72               202
2024                       float64            7.08               197

In [20]:
df_edu[df_edu["1994"].notna()]

,country_name,country_code,indicator_name,indicator_code,1970,1971,1972,1973,1974,1975,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
8,Afghanistan,AFG,"Gross enrolment ratio, secondary, both sexes (%)",SE.SEC.ENRR,8.331610,9.350290,10.348610,10.83169,10.976400,11.04103,...,30.083160,40.223381,46.732761,53.246830,54.616180,56.677341,56.688660,55.656158,55.644409,NaN
15,Afghanistan,AFG,Pupil-teacher ratio in secondary education (he...,SE.SEC.ENRL.TC.ZS,23.137621,22.521250,21.701401,20.51185,21.967581,NaN,...,31.562361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.720879,NaN
18,Afghanistan,AFG,"School life expectancy, primary and secondary,...",UIS.SLE.123,2.380400,2.493640,2.571360,2.62233,2.759030,2.66144,...,8.261090,8.800630,8.937480,9.526070,9.445550,9.936350,10.095130,10.101560,NaN,NaN
20,Afghanistan,AFG,"School life expectancy, secondary, both sexes ...",UIS.SLE.23,0.499900,0.561020,0.620920,0.64990,0.687560,0.66246,...,1.794800,2.413400,2.803970,3.194810,3.276970,3.400640,3.478320,3.384140,NaN,NaN
25,Albania,ALB,"Enrolment in tertiary education per 100,000 in...",UIS.TE_100000.56,NaN,1167.769775,1283.782227,NaN,NaN,NaN,...,2885.000244,3052.736084,3178.929199,4215.400879,4673.476562,5583.394531,6001.114746,6015.172852,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5996,Zambia,ZMB,"School life expectancy, secondary, both sexes ...",UIS.SLE.23,0.647350,0.670670,0.694140,0.67625,0.703310,0.74178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6005,Zimbabwe,ZWE,Government expenditure on education as % of GD...,SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.973330,NaN,8.383220,8.485360,8.429330,NaN,NaN
6008,Zimbabwe,ZWE,"Gross enrolment ratio, secondary, both sexes (%)",SE.SEC.ENRR,7.381360,7.567980,8.159130,8.37640,8.422430,8.68479,...,NaN,NaN,NaN,NaN,NaN,46.673180,47.570190,NaN,NaN,NaN
6022,Zimbabwe,ZWE,Pupil-teacher ratio in secondary education (he...,SE.SEC.ENRL.TC.ZS,NaN,NaN,NaN,19.59516,19.379539,NaN,...,NaN,NaN,NaN,NaN,NaN,22.431910,22.483530,NaN,NaN,NaN
6027,Zimbabwe,ZWE,"School life expectancy, secondary, both sexes ...",UIS.SLE.23,0.442880,0.454080,0.489550,0.50258,0.505350,0.52109,...,NaN,NaN,NaN,NaN,NaN,2.804430,2.858720,NaN,NaN,NaN

In [21]:
edu_config = load_config(EDUCATION_CONFIG)
indicators = edu_config["indicators"]
anzahl_indikatoren = len(indicators)

count_20 = 0
count_10 = 0

for indicator in indicators:
    values = indicators[indicator]
    education_years = values["education_years"]
    if education_years["10"]:
        count_10 += 1
    if education_years["20"]:
        count_20 += 1

print(f"20 Jahre: {count_20} / {anzahl_indikatoren}")
print(f"10 Jahre: {count_10} / {anzahl_indikatoren}")

20 Jahre: 29 / 46
10 Jahre: 34 / 46

In [22]:
short_analysis_frame(df_dev)
df_dev["indicator_name"].unique()

========== DataFrame Qualität ==========


Anzahl Zeilen: 4951
davon: 0 Duplikate

Anzahl Spalten: 30
davon:
    26 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
country_name        str            0.00               214
country_code        str            0.00               214
indicator_name      str            0.00                26
indicator_code      str            0.00                26
1999            float64           35.93              2680
2000            float64           26.56              3108
2001            float64           33.91              2808
2002            float64           24.92              3197
2003            float64           24.92              3173
2004            float64           21.33              3330
2005            float64           21.47              3324
2006            float64           18.58              3459
2007            float64           16.60              3545
2008            float64           14.62              3626
2009            float64           13.84              3646
2010            float64           13.01              3649
2011            float64           13.09              3650
2012            float64           12.36              3737
2013            float64           12.44              3724
2014            float64           11.65              3760
2015            float64           11.17              3775
2016            float64           10.99              3783
2017            float64           10.60              3824
2018            float64           10.22              3811
2019            float64           11.07              3803
2020            float64           11.96              3779
2021            float64           12.58              3718
2022            float64           18.36              3545
2023            float64           23.35              3360
2024            float64           38.21              2743

<ArrowStringArray>
[                                                       'Exports of goods and services (% of GDP)',
                                                              'GDP per capita (constant 2015 US$)',
                           'Government Effectiveness - Governance estimate (approx. -2.5 to +2.5)',
                                             'High-technology exports (% of manufactured exports)',
                                                        'Imports of goods and services (% of GDP)',
                                                'Individuals using the Internet (% of population)',
                                       'Industry (including construction), value added (% of GDP)',
                                                      'Intentional homicides (per 100,000 people)',
 'Labor force with advanced education (% of total working-age population with advanced education)',
                                                         'Life expectancy at birth, total (years)',
                                                           'Manufacturing, value added (% of GDP)',
                            'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
                                                  'Mortality rate, infant (per 1,000 live births)',
                                                 'Mortality rate, under-5 (per 1,000 live births)',
                            'New business density (new registrations per 1,000 people ages 15-64)',
                                                                   'Physicians (per 1,000 people)',
                          'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
                                'Political Stability - Governance estimate (approx. -2.5 to +2.5)',
                                           'Prevalence of HIV, total (% of population ages 15-49)',
                              'Renewable energy consumption (% of total final energy consumption)',
                      'Total greenhouse gas emissions excluding LULUCF per capita (t CO2e/capita)',
                             'Unemployment, total (% of total labor force) (modeled ILO estimate)',
                                                                                      'Gini index',
                             'Poverty headcount ratio at $8.30 a day (2021 PPP) (% of population)',
                                                 'Research and development expenditure (% of GDP)',
                                                      'Trademark applications, resident, by count']
Length: 26, dtype: str

In [23]:
df_dev.head()

,country_name,country_code,indicator_name,indicator_code,1999,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.420817,14.342153,18.380042,16.235278,15.702752
1,Afghanistan,AFG,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,308.318270,277.118051,338.139974,346.071627,338.637274,...,565.569730,563.872337,562.769574,553.125152,557.861533,527.834554,408.625855,377.665627,378.066303,374.376696
2,Afghanistan,AFG,Government Effectiveness - Governance estimate...,GOV_WGI_GE_EST,NaN,-2.344602,NaN,-2.098876,-2.108121,-1.156126,...,-1.471172,-1.417730,-1.442187,-1.631250,-1.654080,-1.716728,-1.705904,-1.964611,-2.092459,-1.933997
3,Afghanistan,AFG,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.289077,37.069564,54.505427,50.764300,68.060273

In [24]:
year_columns = [
    col 
    for col in df_dev.columns 
    if col.isdigit()
]

df_zero = df_dev[(df_dev[year_columns] == 0).any(axis=1)]

df_zero

,country_name,country_code,indicator_name,indicator_code,1999,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
3,Afghanistan,AFG,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
82,American Samoa,ASM,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.200000,0.200000,0.300000,0.300000,0.400000,0.400000,0.400000,0.400000,NaN,NaN
129,Antigua and Barbuda,ATG,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.026056,0.375050,0.613427,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
145,Antigua and Barbuda,ATG,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.400000,0.400000,0.400000,0.700000,0.700000,0.900000,0.900000,0.900000,NaN,NaN
292,"Bahamas, The",BHS,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,2.104437,7.802953,1.966442,1.205449,3.044763,0.261200,0.000000,0.013825,0.000000
307,"Bahamas, The",BHS,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.400000,0.400000,1.5,1.600000,...,1.400000,1.200000,1.100000,1.100000,1.100000,1.400000,1.100000,1.100000,NaN,NaN
329,Bahrain,BHR,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
436,Belize,BLZ,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000082,0.066546,0.000000,0.938241,0.191640,0.000182,0.000000,0.000191
642,Brunei Darussalam,BRN,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
725,Cabo Verde,CPV,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000096,1.323279,0.760205,2.038021,3.476540,1.152150,NaN
833,Cayman Islands,CYM,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
883,Channel Islands,CHI,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,Cyprus,CYP,Poverty headcount ratio at $8.30 a day (2021 P...,SI.POV.UMIC,NaN,NaN,NaN,NaN,NaN,0.300000,...,0.200000,0.100000,0.200000,0.300000,0.500000,0.200000,0.100000,0.000000,0.100000,NaN
1248,Dominica,DMA,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.623349,8.330018,5.331809,16.905065,1.694410,3.305331,27.594663,2.883282,NaN
1610,"Gambia, The",GMB,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.064935,0.000000,0.360381,1.741530,0.040955,0.886699,0.000736,3.212488,2.342310,3.347579
1945,"Hong Kong SAR, China",HKG,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.100000,0.000000,0.100000,0.100000,0.1,0.100000,...,0.200000,0.200000,0.200000,0.200000,0.200000,0.300000,0.400000,NaN,NaN,NaN
1983,Iceland,ISL,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,0.720856,1.777588,0.350813,1.390787,NaN,NaN,...,0.906477,0.297997,0.873282,0.850210,0.277239,1.363832,0.536706,1.051648,1.290131,NaN
2336,"Korea, Dem. People's Rep.",PRK,Individuals using the Internet (% of population),IT.NET.USER.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2406,Kuwait,KWT,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.100000,0.100000,0.100000,NaN,NaN,NaN
2583,Liechtenstein,LIE,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,3.055581,NaN,NaN,NaN,NaN,2.907949,...,NaN,NaN,2.641973,2.622710,2.601457,2.579514,5.122426,NaN,NaN,NaN
2636,Luxembourg,LUX,Poverty headcount ratio at $8.30 a day (2021 P...,SI.POV.UMIC,0.000000,0.000000,0.000000,0.100000,0.5,0.100000,...,0.800000,0.600000,1.100000,0.800000,0.300000,0.000000,0.500000,0.200000,0.200000,NaN
2645,"Macao SAR, China",MAC,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,16.191448,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2792,Malta,MLT,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,2.519599,1.000263,1.489630,1.479419,NaN,1.704003,...,0.898916,1.098252,1.923478,1.650991,0.992033,1.350813,0.381405,1.514601,0.562898,NaN
2805,Malta,MLT,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.100000,0.1,0.100000,...,6.000000,9.200000,7.300000,7.600000,7.400000,9.200000,8.600000,NaN,NaN,NaN
3315,Northern Mariana Islands,MNP,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000,0.500000,0.500000,NaN,NaN
3362,Oman,OMN,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.100000,NaN,NaN,NaN
3410,Palau,PLW,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.400000,0.600000,0.600000,0.600000,0.900000,0.900000,0.900000,0.900000,NaN,NaN
3630,Qatar,QAT,Poverty headcount ratio at $8.30 a day (2021 P...,SI.POV.UMIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3632,Qatar,QAT,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.100000,0.100000,0.100000,0.100000,0.0,0.000000,...,0.000000,0.100000,0.100000,0.000000,0.100000,0.000000,0.000000,NaN,NaN,NaN
3797,Saudi Arabia,SAU,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.100000,NaN,NaN,NaN
3930,Sint Maarten (Dutch part),SXM,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
4142,St. Kitts and Nevis,KNA,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,27.200000,26.400000,26.000000,24.300000,26.3,22.000000,...,1.600000,1.700000,1.300000,1.300000,1.300000,1.600000,1.600000,1.500000,NaN,NaN
4173,St. Vincent and the Grenadines,VCT,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.004010,0.000820,0.001089,9.926176,0.000000,0.003450,4.007087,4.934429,NaN
4287,Switzerland,CHE,Poverty headcount ratio at $8.30 a day (2021 P...,SI.POV.UMIC,NaN,0.400000,NaN,0.200000,NaN,0.600000,...,0.100000,0.200000,0.100000,0.200000,0.200000,0.100000,0.200000,0.300000,NaN,NaN
4401,Timor-Leste,TLS,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,0.000000,NaN,NaN,...,18.600000,21.200001,24.200001,27.600000,28.004601,32.012699,35.042000,NaN,NaN,NaN
4447,Tonga,TON,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.902178,2.169692,1.127860,3.733362,1.689960,0.552737,28.460295,NaN
4553,Turkmenistan,TKM,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.100000,0.100000,0.100000,0.100000,0.1,0.100000,...,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,NaN,NaN,NaN
4587,Tuvalu,TUV,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,3.000000,7.300000,7.000000,6.400000,6.300000,5.000000,5.000000,5.200000,NaN,NaN
4659,United Arab Emirates,ARE,Poverty headcount ratio at $8.30 a day (2021 P...,SI.POV.UMIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.600000,NaN,NaN,NaN,NaN,NaN,NaN
4790,"Venezuela, RB",VEN,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,40.754717,31.197772,33.333333,42.547125,47.195726,13.005444,15.350053,16.349094,18.066367,16.735034
4794,"Venezuela, RB",VEN,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,19.622642,10.194986,9.281609,12.086171,10.933114,13.085123,13.876334,11.548960,10.028066,9.502355
4796,"Venezuela, RB",VEN,"Industry (including construction), value added...",NV.IND.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4800,"Venezuela, RB",VEN,"Manufacturing, value added (% of GDP)",NV.IND.MANF.ZS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_dev = pd.read_csv(DEVELOPMENT_OUTPUT, encoding="utf-8")

dev_config = load_config(DEVELOPMENT_CONFIG)

df_dev_armut = df_dev[df_dev["indicator_code"] == "VC.IHR.PSRC.P5"]

df_dev_armut = create_dev_change_columns(df_dev_armut, dev_config)

df_dev_armut.sort_values("country_name")

short_analysis_frame(df_dev_armut)

========== DataFrame Qualität ==========


Anzahl Zeilen: 193
davon: 0 Duplikate

Anzahl Spalten: 32
davon:
    28 numerisch
    0 datetime
    4 string/object
    0 kategorial

                     Datentyp  Fehlende Werte  Eindeutige Werte
country_name              str            0.00               193
country_code              str            0.00               193
indicator_name            str            0.00                 1
indicator_code            str            0.00                 1
1999                  float64           46.11               104
2000                  float64           39.38               117
2001                  float64           34.20               127
2002                  float64           33.16               129
2003                  float64           43.01               110
2004                  float64           34.72               126
2005                  float64           36.27               123
2006                  float64           32.64               129
2007                  float64           26.42               142
2008                  float64           21.24               152
2009                  float64           22.80               149
2010                  float64           19.17               156
2011                  float64           23.83               147
2012                  float64           23.83               147
2013                  float64           33.68               128
2014                  float64           34.20               127
2015                  float64           32.64               130
2016                  float64           33.68               128
2017                  float64           32.12               131
2018                  float64           33.16               129
2019                  float64           31.09               133
2020                  float64           33.16               129
2021                  float64           39.90               116
2022                  float64           45.60               105
2023                  float64           56.99                83
2024                  float64          100.00                 0
change_over_10_years  float64           45.60               105
change_over_20_years  float64           46.11               104

In [26]:
df_dev_armut.sort_values("change_over_10_years").head(20)

,country_name,country_code,indicator_name,indicator_code,1999,2000,2001,2002,2003,2004,...,2017,2018,2019,2020,2021,2022,2023,2024,change_over_10_years,change_over_20_years
4797,"Venezuela, RB",VEN,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,24.822790,32.707202,31.865593,37.809107,43.803846,36.897080,...,47.979208,NaN,41.032413,29.475380,19.279105,12.646645,NaN,NaN,-41.735484,-25.162462
1914,Honduras,HND,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,40.043978,48.283823,51.612957,52.213199,57.211380,49.856182,...,40.299802,37.981772,41.011166,35.702849,38.202597,34.967935,31.442432,NaN,-40.903155,-25.768948
1350,El Salvador,SLV,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,65.016312,59.747288,60.153551,47.355520,55.946401,64.899476,...,63.764040,53.795877,38.538696,21.508745,17.343956,7.897688,NaN,NaN,-34.529702,-39.457832
440,Belize,BLZ,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,NaN,17.026649,25.767126,33.983247,25.399955,29.077418,...,38.049150,37.609162,34.730457,26.099539,31.617834,28.058292,NaN,NaN,-15.301137,-5.924955
3599,Puerto Rico (US),PRI,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,15.627981,19.265769,21.033235,21.518286,21.492138,22.192057,...,21.590371,20.181954,19.251661,16.972927,19.426966,17.649045,14.589658,NaN,-11.028839,-6.902479
1792,Guatemala,GTM,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,23.242652,24.825622,26.985430,29.648282,33.826071,35.190587,...,32.805474,28.903544,25.941600,18.188286,20.245871,22.047440,23.365727,NaN,-10.135846,-10.460344
606,Brazil,BRA,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,25.002106,26.074847,27.200608,27.848196,28.271088,26.491836,...,31.161176,27.160615,21.244560,21.812909,20.504863,20.081175,19.275296,NaN,-9.365115,-8.995793
946,Colombia,COL,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,63.333992,67.892159,70.109587,70.396095,57.460863,48.648188,...,25.551059,23.820759,23.399061,22.642703,25.580127,24.948808,24.913442,NaN,-8.502529,-32.547421
1273,Dominican Republic,DOM,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,12.621048,14.095681,12.556931,14.448329,21.178939,24.591176,...,11.399812,9.905349,9.417991,8.729777,10.536275,12.367848,10.916698,NaN,-8.487192,-10.262241
3420,Panama,PAN,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,9.655054,9.932339,9.968932,12.015298,10.564903,9.473558,...,9.222421,9.621243,11.334922,11.646159,12.657048,11.338917,11.707293,NaN,-5.624547,1.142391
2270,Kazakhstan,KAZ,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,15.359856,14.998933,13.867889,12.563330,12.643373,13.192296,...,4.905658,NaN,NaN,3.110545,2.846492,2.550586,NaN,NaN,-4.764751,-10.012743
2935,Moldova,MDA,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,9.139325,10.224402,9.809608,9.679141,7.789190,6.845135,...,4.415222,5.263537,3.887473,3.030174,2.182700,2.467118,2.543144,NaN,-4.174886,-5.246046
3524,Philippines,PHL,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,7.334741,7.202476,7.189058,7.888633,NaN,NaN,...,7.647081,5.162367,4.299457,NaN,NaN,NaN,4.347591,NaN,-4.121544,-3.541042
2599,Lithuania,LTU,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,8.771179,10.570215,10.164112,8.507425,NaN,10.157849,...,3.534428,3.282809,3.363079,3.612608,2.576501,2.378485,2.627800,NaN,-4.065097,-5.879625
3472,Paraguay,PRY,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,NaN,19.506484,25.329198,26.077066,24.124947,22.438026,...,8.534926,7.732542,8.503378,7.283752,7.854364,7.573445,6.779516,NaN,-3.316690,-17.345431
30,Albania,ALB,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,16.684462,4.137520,6.988690,6.891948,5.323776,4.227637,...,2.001213,2.280398,2.253026,2.123990,2.316086,1.697548,1.387083,NaN,-2.877643,-3.936693
156,Argentina,ARG,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,NaN,NaN,8.316318,9.387486,7.721680,6.023302,...,5.231560,5.338722,5.131915,5.352721,4.621264,4.312025,4.492911,NaN,-2.721327,-3.228768
1414,Estonia,EST,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,11.185702,10.236242,9.869098,10.294070,NaN,NaN,...,2.201265,2.118060,1.959570,3.158680,1.952319,1.481381,1.535990,NaN,-2.409622,-8.758079
3350,Oman,OMN,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,NaN,NaN,NaN,1.198045,1.480670,1.746492,...,0.374664,0.282739,0.500954,0.309564,0.244421,0.253688,0.138634,NaN,-2.391418,-1.342036
3375,Pakistan,PAK,"Intentional homicides (per 100,000 people)",VC.IHR.PSRC.P5,6.197972,5.750291,6.023071,5.799444,5.592715,5.612835,...,3.688294,3.631534,3.472257,3.553165,3.786572,4.077543,4.334871,NaN,-2.268027,-1.257844