In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from utils.hilfsfunktionen import create_frames, select_dataframe, find_relevant_years, short_analysis_frame
from src.paths import (
    EDUCATION_RAW,
    COUNTRY_INFO,
    EDUCATION_OUTPUT,
    DEVELOPMENT_OUTPUT
)

df1 = pd.read_csv(COUNTRY_INFO, encoding="utf-8")
df2 = pd.read_csv(EDUCATION_RAW, encoding="utf-8")

In [3]:
df1.head(10)

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,...,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN,NaN
5,ARB,Arab World,Arab World,Arab World,1A,NaN,Arab World aggregate. Arab World is composed o...,NaN,NaN,1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,April 2013 database update: Based on data from...,Middle East & North Africa,High income: nonOECD,AE,...,General Data Dissemination System (GDDS),2010,NaN,NaN,NaN,2012,NaN,2011.0,2005,NaN
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,...,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2012.0,2000,NaN
8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Lower middle income,AM,...,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey (DHS), 2010","Integrated household survey (IHS), 2012",Yes,2013/14,NaN,2012.0,2007,NaN
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN,NaN

In [4]:
df2.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.365540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"Adjusted net enrolment rate, primary, female (%)",SE.PRM.TENR.FE,43.351101,43.318150,44.640701,45.845718,46.449501,48.363892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Arab World,ARB,"Adjusted net enrolment rate, primary, gender p...",UIS.NERA.1.GPI,0.658570,0.656400,0.663290,0.672040,0.672610,0.691760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arab World,ARB,"Adjusted net enrolment rate, primary, male (%)",SE.PRM.TENR.MA,65.826233,65.993584,67.301857,68.219078,69.059013,69.914551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2.shape

(886930, 70)

In [6]:
df2.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.365540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"Adjusted net enrolment rate, primary, female (%)",SE.PRM.TENR.FE,43.351101,43.318150,44.640701,45.845718,46.449501,48.363892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Arab World,ARB,"Adjusted net enrolment rate, primary, gender p...",UIS.NERA.1.GPI,0.658570,0.656400,0.663290,0.672040,0.672610,0.691760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arab World,ARB,"Adjusted net enrolment rate, primary, male (%)",SE.PRM.TENR.MA,65.826233,65.993584,67.301857,68.219078,69.059013,69.914551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
indicators = list(df2["Indicator Name"].unique())
indicators

['Adjusted net enrolment rate, lower secondary, both sexes (%)',
 'Adjusted net enrolment rate, lower secondary, female (%)',
 'Adjusted net enrolment rate, lower secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, lower secondary, male (%)',
 'Adjusted net enrolment rate, primary, both sexes (%)',
 'Adjusted net enrolment rate, primary, female (%)',
 'Adjusted net enrolment rate, primary, gender parity index (GPI)',
 'Adjusted net enrolment rate, primary, male (%)',
 'Adjusted net enrolment rate, upper secondary, both sexes (%)',
 'Adjusted net enrolment rate, upper secondary, female (%)',
 'Adjusted net enrolment rate, upper secondary, gender parity index (GPI)',
 'Adjusted net enrolment rate, upper secondary, male (%)',
 'Adjusted net intake rate to Grade 1 of primary education, both sexes (%)',
 'Adjusted net intake rate to Grade 1 of primary education, female (%)',
 'Adjusted net intake rate to Grade 1 of primary education, gender parity index (GPI)',
 'Adjusted net intake rate to Grade 1 of primary education, male (%)',
 'Adult illiterate population, 15+ years, % female',
 'Adult illiterate population, 15+ years, both sexes (number)',
 'Adult illiterate population, 15+ years, female (number)',
 'Adult illiterate population, 15+ years, male (number)',
 'Adult literacy rate, population 15+ years, both sexes (%)',
 'Adult literacy rate, population 15+ years, female (%)',
 'Adult literacy rate, population 15+ years, gender parity index (GPI)',
 'Adult literacy rate, population 15+ years, male (%)',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes, female (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes, level unspecified, female (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, both sexes (number)',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes, female (number)',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained, female (%)',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained, female (%)',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited, female (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained, male (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained, male (%)',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited, male (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained, both sexes (%)',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited, both sexes (%)',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education, male',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, both sexes',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, female',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education, male',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public lower secondary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public primary education, male (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, both sexes (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, female (%)',
 'Africa Dataset: Teacher attrition rate from public upper secondary education, male (%)',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Top of scale',
 'Barro-Lee: Average years of primary schooling, age 15+, female',
 'Barro-Lee: Average years of primary schooling, age 15+, total',
 'Barro-Lee: Average years of primary schooling, age 15-19, female',
 'Barro-Lee: Average years of primary schooling, age 15-19, total',
 'Barro-Lee: Average years of primary schooling, age 20-24, female',
 'Barro-Lee: Average years of primary schooling, age 20-24, total',
 'Barro-Lee: Average years of primary schooling, age 25+, female',
 'Barro-Lee: Average years of primary schooling, age 25+, total',
 'Barro-Lee: Average years of primary schooling, age 25-29, female',
 'Barro-Lee: Average years of primary schooling, age 25-29, total',
 'Barro-Lee: Average years of primary schooling, age 30-34, female',
 'Barro-Lee: Average years of primary schooling, age 30-34, total',
 'Barro-Lee: Average years of primary schooling, age 35-39, female',
 'Barro-Lee: Average years of primary schooling, age 35-39, total',
 'Barro-Lee: Average years of primary schooling, age 40-44, female',
 'Barro-Lee: Average years of primary schooling, age 40-44, total',
 'Barro-Lee: Average years of primary schooling, age 45-49, female',
 'Barro-Lee: Average years of primary schooling, age 45-49, total',
 'Barro-Lee: Average years of primary schooling, age 50-54, female',
 'Barro-Lee: Average years of primary schooling, age 50-54, total',
 'Barro-Lee: Average years of primary schooling, age 55-59, female',
 'Barro-Lee: Average years of primary schooling, age 55-59, total',
 'Barro-Lee: Average years of primary schooling, age 60-64, female',
 'Barro-Lee: Average years of primary schooling, age 60-64, total',
 'Barro-Lee: Average years of primary schooling, age 65-69, female',
 'Barro-Lee: Average years of primary schooling, age 65-69, total',
 'Barro-Lee: Average years of primary schooling, age 70-74, female',
 'Barro-Lee: Average years of primary schooling, age 70-74, total',
 'Barro-Lee: Average years of primary schooling, age 75+, female',
 'Barro-Lee: Average years of primary schooling, age 75+, total',
 'Barro-Lee: Average years of secondary schooling, age 15+, female',
 'Barro-Lee: Average years of secondary schooling, age 15+, total',
 'Barro-Lee: Average years of secondary schooling, age 15-19, female',
 'Barro-Lee: Average years of secondary schooling, age 15-19, total',
 'Barro-Lee: Average years of secondary schooling, age 20-24, female',
 'Barro-Lee: Average years of secondary schooling, age 20-24, total',
 'Barro-Lee: Average years of secondary schooling, age 25+, female',
 'Barro-Lee: Average years of secondary schooling, age 25+, total',
 'Barro-Lee: Average years of secondary schooling, age 25-29, female',
 'Barro-Lee: Average years of secondary schooling, age 25-29, total',
 'Barro-Lee: Average years of secondary schooling, age 30-34, female',
 'Barro-Lee: Average years of secondary schooling, age 30-34, total',
 'Barro-Lee: Average years of secondary schooling, age 35-39, female',
 'Barro-Lee: Average years of secondary schooling, age 35-39, total',
 'Barro-Lee: Average years of secondary schooling, age 40-44, female',
 'Barro-Lee: Average years of secondary schooling, age 40-44, total',
 'Barro-Lee: Average years of secondary schooling, age 45-49, female',
 'Barro-Lee: Average years of secondary schooling, age 45-49, total',
 'Barro-Lee: Average years of secondary schooling, age 50-54, female',
 'Barro-Lee: Average years of secondary schooling, age 50-54, total',
 'Barro-Lee: Average years of secondary schooling, age 55-59, female',
 'Barro-Lee: Average years of secondary schooling, age 55-59, total',
 'Barro-Lee: Average years of secondary schooling, age 60-64, female',
 'Barro-Lee: Average years of secondary schooling, age 60-64, total',
 'Barro-Lee: Average years of secondary schooling, age 65-69, female',
 'Barro-Lee: Average years of secondary schooling, age 65-69, total',
 'Barro-Lee: Average years of secondary schooling, age 70-74, female',
 'Barro-Lee: Average years of secondary schooling, age 70-74, total',
 'Barro-Lee: Average years of secondary schooling, age 75+, female',
 'Barro-Lee: Average years of secondary schooling, age 75+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15+, female',
 'Barro-Lee: Average years of tertiary schooling, age 15+, total',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, female',
 'Barro-Lee: Average years of tertiary schooling, age 15-19, total',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, female',
 'Barro-Lee: Average years of tertiary schooling, age 20-24, total',
 'Barro-Lee: Average years of tertiary schooling, age 25+, female',
 'Barro-Lee: Average years of tertiary schooling, age 25+, total',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, female',
 'Barro-Lee: Average years of tertiary schooling, age 25-29, total',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, female',
 'Barro-Lee: Average years of tertiary schooling, age 30-34, total',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, female',
 'Barro-Lee: Average years of tertiary schooling, age 35-39, total',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, female',
 'Barro-Lee: Average years of tertiary schooling, age 40-44, total',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, female',
 'Barro-Lee: Average years of tertiary schooling, age 45-49, total',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, female',
 'Barro-Lee: Average years of tertiary schooling, age 50-54, total',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, female',
 'Barro-Lee: Average years of tertiary schooling, age 55-59, total',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, female',
 'Barro-Lee: Average years of tertiary schooling, age 60-64, total',

In [8]:
indicators_group = []
for ind in indicators:
    parts = ind.split(",")
    first_part = parts[0]
    if first_part not in indicators_group:
        indicators_group.append(first_part)

indicators_group

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education',
 'Africa Dataset: Teacher attrition rate from public primary education',
 'Africa Dataset: Teacher attrition rate from public upper secondary education',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Lower Secondary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Pre-Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Primary. Top of scale',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 10 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. 15 years of experience',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Starting salary',
 'Annual statutory teacher salaries in public institutions in USD. Upper Secondary. Top of scale',
 'Barro-Lee: Average years of primary schooling',
 'Barro-Lee: Average years of secondary schooling',
 'Barro-Lee: Average years of tertiary schooling',
 'Barro-Lee: Average years of total schooling',
 'Barro-Lee: Percentage of female population age 15+ with no education',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 15-19 with no education',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 20-24 with no education',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 25+ with no education',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 25-29 with no education',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 30-34 with no education',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 35-39 with no education',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 40-44 with no education',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 45-49 with no education',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 50-54 with no education',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 55-59 with no education',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 60-64 with no education',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling. Completed Primary',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling. Total (Incomplete and Completed Primary)',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling. Total (Incomplete and Completed Secondary)',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling. Completed Tertiary',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling. Total (Incomplete and Completed Tertiary)',
 'Barro-Lee: Percentage of female population age 65-69 with no education',
 'Barro-Lee: Percentage of female population age 65-69 with primary schooling. Completed Primary',

In [9]:
indicators_group2 = []
for ind in indicators_group:
    parts = ind.split(".")
    first_part = parts[0]
    if first_part not in indicators_group2:
        indicators_group2.append(first_part)

indicators_group2

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per mathematics textbook in primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 1 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 2 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 3 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 4 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 5 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 6 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in Grade 7 of primary education (number)',
 'Africa Dataset: Average number of pupils per reading textbook in primary education (number)',
 'Africa Dataset: Average size of classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of multigrade classes in primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 1 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 2 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 3 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 4 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 5 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 6 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in Grade 7 of primary schools (number of pupils)',
 'Africa Dataset: Average size of single grade classes in primary schools (number of pupils)',
 'Africa Dataset: Graduates from accredited pre-service lower secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary or secondary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service primary teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service teacher training programmes',
 'Africa Dataset: Graduates from accredited pre-service upper secondary teacher training programmes',
 'Africa Dataset: Percentage of female newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of female newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of female teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of female teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of lower secondary schools with access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools with toilets (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to electricity (%)',
 'Africa Dataset: Percentage of lower secondary schools without access to potable water (%)',
 'Africa Dataset: Percentage of lower secondary schools without toilets (%)',
 'Africa Dataset: Percentage of male newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of male newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of male teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of male teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in lower secondary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in primary education who are trained',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are female (%)',
 'Africa Dataset: Percentage of newly recruited teachers in upper secondary education who are trained',
 'Africa Dataset: Percentage of primary pupils in multigrade classes (%)',
 'Africa Dataset: Percentage of primary schools with access to electricity (%)',
 'Africa Dataset: Percentage of primary schools with access to potable water (%)',
 'Africa Dataset: Percentage of primary schools with mixed-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with no information on electricity (%)',
 'Africa Dataset: Percentage of primary schools with no information on potable water (%)',
 'Africa Dataset: Percentage of primary schools with no information on toilets (%)',
 'Africa Dataset: Percentage of primary schools with single-sex toilets (%)',
 'Africa Dataset: Percentage of primary schools with toilets (%)',
 'Africa Dataset: Percentage of primary schools without access to electricity (%)',
 'Africa Dataset: Percentage of primary schools without access to potable water (%)',
 'Africa Dataset: Percentage of primary schools without toilets (%)',
 'Africa Dataset: Percentage of teachers in lower secondary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in primary education who are newly recruited',
 'Africa Dataset: Percentage of teachers in upper secondary education who are newly recruited',
 'Africa Dataset: Ratio of teacher training graduates to teachers in lower secondary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in primary education',
 'Africa Dataset: Ratio of teacher training graduates to teachers in upper secondary education',
 'Africa Dataset: School census return rate from primary schools',
 'Africa Dataset: School census return rate from secondary schools',
 'Africa Dataset: Teacher attrition rate from public lower secondary education',
 'Africa Dataset: Teacher attrition rate from public primary education',
 'Africa Dataset: Teacher attrition rate from public upper secondary education',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD',
 'Barro-Lee: Average years of primary schooling',
 'Barro-Lee: Average years of secondary schooling',
 'Barro-Lee: Average years of tertiary schooling',
 'Barro-Lee: Average years of total schooling',
 'Barro-Lee: Percentage of female population age 15+ with no education',
 'Barro-Lee: Percentage of female population age 15+ with primary schooling',
 'Barro-Lee: Percentage of female population age 15+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 15+ with tertiary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with no education',
 'Barro-Lee: Percentage of female population age 15-19 with primary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with secondary schooling',
 'Barro-Lee: Percentage of female population age 15-19 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with no education',
 'Barro-Lee: Percentage of female population age 20-24 with primary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with secondary schooling',
 'Barro-Lee: Percentage of female population age 20-24 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 25+ with no education',
 'Barro-Lee: Percentage of female population age 25+ with primary schooling',
 'Barro-Lee: Percentage of female population age 25+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 25+ with tertiary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with no education',
 'Barro-Lee: Percentage of female population age 25-29 with primary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with secondary schooling',
 'Barro-Lee: Percentage of female population age 25-29 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with no education',
 'Barro-Lee: Percentage of female population age 30-34 with primary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with secondary schooling',
 'Barro-Lee: Percentage of female population age 30-34 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with no education',
 'Barro-Lee: Percentage of female population age 35-39 with primary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with secondary schooling',
 'Barro-Lee: Percentage of female population age 35-39 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with no education',
 'Barro-Lee: Percentage of female population age 40-44 with primary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with secondary schooling',
 'Barro-Lee: Percentage of female population age 40-44 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with no education',
 'Barro-Lee: Percentage of female population age 45-49 with primary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with secondary schooling',
 'Barro-Lee: Percentage of female population age 45-49 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with no education',
 'Barro-Lee: Percentage of female population age 50-54 with primary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with secondary schooling',
 'Barro-Lee: Percentage of female population age 50-54 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with no education',
 'Barro-Lee: Percentage of female population age 55-59 with primary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with secondary schooling',
 'Barro-Lee: Percentage of female population age 55-59 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with no education',
 'Barro-Lee: Percentage of female population age 60-64 with primary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with secondary schooling',
 'Barro-Lee: Percentage of female population age 60-64 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with no education',
 'Barro-Lee: Percentage of female population age 65-69 with primary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with secondary schooling',
 'Barro-Lee: Percentage of female population age 65-69 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with no education',
 'Barro-Lee: Percentage of female population age 70-74 with primary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with secondary schooling',
 'Barro-Lee: Percentage of female population age 70-74 with tertiary schooling',
 'Barro-Lee: Percentage of female population age 75+ with no education',
 'Barro-Lee: Percentage of female population age 75+ with primary schooling',
 'Barro-Lee: Percentage of female population age 75+ with secondary schooling',
 'Barro-Lee: Percentage of female population age 75+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 15+ with no education',
 'Barro-Lee: Percentage of population age 15+ with primary schooling',
 'Barro-Lee: Percentage of population age 15+ with secondary schooling',
 'Barro-Lee: Percentage of population age 15+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 15-19 with no education',
 'Barro-Lee: Percentage of population age 15-19 with primary schooling',
 'Barro-Lee: Percentage of population age 15-19 with secondary schooling',
 'Barro-Lee: Percentage of population age 15-19 with tertiary schooling',
 'Barro-Lee: Percentage of population age 20-24 with no education',
 'Barro-Lee: Percentage of population age 20-24 with primary schooling',
 'Barro-Lee: Percentage of population age 20-24 with secondary schooling',
 'Barro-Lee: Percentage of population age 20-24 with tertiary schooling',
 'Barro-Lee: Percentage of population age 25+ with no education',
 'Barro-Lee: Percentage of population age 25+ with primary schooling',
 'Barro-Lee: Percentage of population age 25+ with secondary schooling',
 'Barro-Lee: Percentage of population age 25+ with tertiary schooling',
 'Barro-Lee: Percentage of population age 25-29 with no education',
 'Barro-Lee: Percentage of population age 25-29 with primary schooling',
 'Barro-Lee: Percentage of population age 25-29 with secondary schooling',
 'Barro-Lee: Percentage of population age 25-29 with tertiary schooling',
 'Barro-Lee: Percentage of population age 30-34 with no education',
 'Barro-Lee: Percentage of population age 30-34 with primary schooling',
 'Barro-Lee: Percentage of population age 30-34 with secondary schooling',
 'Barro-Lee: Percentage of population age 30-34 with tertiary schooling',
 'Barro-Lee: Percentage of population age 35-39 with no education',
 'Barro-Lee: Percentage of population age 35-39 with primary schooling',
 'Barro-Lee: Percentage of population age 35-39 with secondary schooling',
 'Barro-Lee: Percentage of population age 35-39 with tertiary schooling',
 'Barro-Lee: Percentage of population age 40-44 with no education',
 'Barro-Lee: Percentage of population age 40-44 with primary schooling',
 'Barro-Lee: Percentage of population age 40-44 with secondary schooling',
 'Barro-Lee: Percentage of population age 40-44 with tertiary schooling',
 'Barro-Lee: Percentage of population age 45-49 with no education',
 'Barro-Lee: Percentage of population age 45-49 with primary schooling',
 'Barro-Lee: Percentage of population age 45-49 with secondary schooling',
 'Barro-Lee: Percentage of population age 45-49 with tertiary schooling',
 'Barro-Lee: Percentage of population age 50-54 with no education',
 'Barro-Lee: Percentage of population age 50-54 with primary schooling',
 'Barro-Lee: Percentage of population age 50-54 with secondary schooling',
 'Barro-Lee: Percentage of population age 50-54 with tertiary schooling',
 'Barro-Lee: Percentage of population age 55-59 with no education',
 'Barro-Lee: Percentage of population age 55-59 with primary schooling',
 'Barro-Lee: Percentage of population age 55-59 with secondary schooling',
 'Barro-Lee: Percentage of population age 55-59 with tertiary schooling',
 'Barro-Lee: Percentage of population age 60-64 with no education',
 'Barro-Lee: Percentage of population age 60-64 with primary schooling',
 'Barro-Lee: Percentage of population age 60-64 with secondary schooling',
 'Barro-Lee: Percentage of population age 60-64 with tertiary schooling',
 'Barro-Lee: Percentage of population age 65-69 with no education',
 'Barro-Lee: Percentage of population age 65-69 with primary schooling',
 'Barro-Lee: Percentage of population age 65-69 with secondary schooling',
 'Barro-Lee: Percentage of population age 65-69 with tertiary schooling',
 'Barro-Lee: Percentage of population age 70-74 with no education',
 'Barro-Lee: Percentage of population age 70-74 with primary schooling',
 'Barro-Lee: Percentage of population age 70-74 with secondary schooling',
 'Barro-Lee: Percentage of population age 70-74 with tertiary schooling',
 'Barro-Lee: Percentage of population age 75+ with no education',
 'Barro-Lee: Percentage of population age 75+ with primary schooling',
 'Barro-Lee: Percentage of population age 75+ with secondary schooling',
 'Barro-Lee: Percentage of population age 75+ with tertiary schooling',
 'Barro-Lee: Population in thousands',
 'Capital expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Capital expenditure as % of total expenditure in primary public institutions (%)',
 'Capital expenditure as % of total expenditure in public institutions (%)',
 'Capital expenditure as % of total expenditure in secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Cumulative drop-out rate to the last grade of lower secondary general education',
 'Cumulative drop-out rate to the last grade of primary education',
 'Current expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure as % of total expenditure in primary public institutions (%)',
 'Current expenditure as % of total expenditure in public institutions (%)',
 'Current expenditure as % of total expenditure in secondary public institutions (%)',
 'Current expenditure as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in upper-secondary public institutions (%)',

In [10]:
indicators_group3 = []
for ind in indicators_group2:
    parts = ind.split(":")
    first_part = parts[0]
    if first_part not in indicators_group3:
        indicators_group3.append(first_part)

indicators_group3

['Adjusted net enrolment rate',
 'Adjusted net intake rate to Grade 1 of primary education',
 'Adult illiterate population',
 'Adult literacy rate',
 'Africa Dataset',
 'All staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'All staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'All staff compensation as % of total expenditure in primary public institutions (%)',
 'All staff compensation as % of total expenditure in public institutions (%)',
 'All staff compensation as % of total expenditure in secondary public institutions (%)',
 'All staff compensation as % of total expenditure in tertiary public institutions (%)',
 'All staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'Annual statutory teacher salaries in public institutions in USD',
 'Barro-Lee',
 'Capital expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Capital expenditure as % of total expenditure in primary public institutions (%)',
 'Capital expenditure as % of total expenditure in public institutions (%)',
 'Capital expenditure as % of total expenditure in secondary public institutions (%)',
 'Capital expenditure as % of total expenditure in tertiary public institutions (%)',
 'Capital expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Cumulative drop-out rate to the last grade of lower secondary general education',
 'Cumulative drop-out rate to the last grade of primary education',
 'Current expenditure as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure as % of total expenditure in primary public institutions (%)',
 'Current expenditure as % of total expenditure in public institutions (%)',
 'Current expenditure as % of total expenditure in secondary public institutions (%)',
 'Current expenditure as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure as % of total expenditure in upper-secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in lower secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in post-secondary non-tertiary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in pre-primary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in primary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in secondary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in tertiary public institutions (%)',
 'Current expenditure other than staff compensation as % of total expenditure in upper secondary public institutions (%)',
 'DHS',
 'Drop-out rate from Grade 1 of lower secondary general education',
 'Drop-out rate from Grade 1 of primary education',
 'Drop-out rate from Grade 2 of lower secondary general education',
 'Drop-out rate from Grade 2 of primary education',
 'Drop-out rate from Grade 3 of lower secondary general education',
 'Drop-out rate from Grade 3 of primary education',
 'Drop-out rate from Grade 4 of lower secondary general education',
 'Drop-out rate from Grade 4 of primary education',
 'Drop-out rate from Grade 5 of lower secondary general education',
 'Drop-out rate from Grade 5 of primary education',
 'Drop-out rate from Grade 6 of primary education',
 'Duration of compulsory education (years)',
 'Early school leavers from primary education',
 'Effective transition rate from primary to lower secondary general education',
 'EGRA',
 'Elderly illiterate population',
 'Elderly literacy rate',
 'Enrolment in early childhood education',
 'Enrolment in early childhood educational development programmes',
 'Enrolment in Grade 1 of lower secondary general education',
 'Enrolment in Grade 1 of primary education',
 'Enrolment in Grade 2 of lower secondary general education',
 'Enrolment in Grade 2 of primary education',
 'Enrolment in Grade 3 of lower secondary general education',
 'Enrolment in Grade 3 of primary education',
 'Enrolment in Grade 4 of lower secondary general education',
 'Enrolment in Grade 4 of primary education',
 'Enrolment in Grade 5 of lower secondary general education',
 'Enrolment in Grade 5 of primary education',
 'Enrolment in Grade 6 of lower secondary general education',
 'Enrolment in Grade 6 of primary education',
 'Enrolment in Grade 7 of primary education',
 'Enrolment in lower secondary education',
 'Enrolment in lower secondary general education',
 'Enrolment in lower secondary general',
 'Enrolment in lower secondary vocational',
 'Enrolment in post-secondary non-tertiary education',
 'Enrolment in pre-primary education',
 'Enrolment in primary education',
 'Enrolment in secondary education',
 'Enrolment in secondary general',
 'Enrolment in secondary vocational',
 'Enrolment in tertiary education per 100',
 'Enrolment in tertiary education',
 'Enrolment in upper secondary education',
 'Enrolment in upper secondary general',
 'Enrolment in upper secondary vocational',
 'Expenditure on education as % of total government expenditure (%)',
 'Expenditure on education not allocated by level as % of government expenditure on education (%)',
 'Expenditure on lower secondary as % of government expenditure on education (%)',
 'Expenditure on lower secondary as % of total government expenditure (%)',
 'Expenditure on post-secondary non-tertiary as % of government expenditure on education (%)',
 'Expenditure on post-secondary non-tertiary as % of total government expenditure (%)',
 'Expenditure on pre-primary as % of government expenditure on education (%)',
 'Expenditure on pre-primary as % of total government expenditure (%)',
 'Expenditure on primary as % of government expenditure on education (%)',
 'Expenditure on primary as % of total government expenditure (%)',
 'Expenditure on secondary and post-secondary non-tertiary vocational as % of government expenditure on education (%)',
 'Expenditure on secondary and post-secondary non-tertiary vocational education as % of total government expenditure (%)',
 'Expenditure on secondary as % of government expenditure on education (%)',
 'Expenditure on secondary as % of total government expenditure (%)',
 'Expenditure on tertiary as % of government expenditure on education (%)',
 'Expenditure on tertiary as % of total government expenditure (%)',
 'Expenditure on upper secondary as % of government expenditure on education (%)',
 'Expenditure on upper secondary as % of total government expenditure (%)',
 'GDP at market prices (constant 2005 US$)',
 'GDP at market prices (current US$)',
 'GDP per capita (constant 2005 US$)',
 'GDP per capita (current US$)',
 'GDP per capita',
 'GDP',
 'GNI (current US$)',
 'GNI per capita',
 'GNI',
 'Government expenditure in educational institutions as % of GDP (%)',
 'Government expenditure in post-secondary non-tertiary institutions as % of GDP (%)',
 'Government expenditure in pre-primary institutions as % of GDP (%)',
 'Government expenditure in primary institutions as % of GDP (%)',
 'Government expenditure in secondary institutions education as % of GDP (%)',
 'Government expenditure in tertiary institutions as % of GDP (%)',
 'Government expenditure on education as % of GDP (%)',
 'Government expenditure on post-secondary non-tertiary education as % of GDP (%)',
 'Government expenditure on pre-primary education as % of GDP (%)',
 'Government expenditure on primary education as % of GDP (%)',
 'Government expenditure on secondary and post-secondary non-tertiary vocational education as % of GDP (%)',
 'Government expenditure on secondary education as % of GDP (%)',
 'Government expenditure on tertiary education as % of GDP (%)',
 'Government expenditure per lower secondary student (constant PPP$)',
 'Government expenditure per lower secondary student (constant US$)',
 'Government expenditure per lower secondary student (PPP$)',
 'Government expenditure per lower secondary student (US$)',
 'Government expenditure per lower secondary student as % of GDP per capita (%)',
 'Government expenditure per post-secondary non-tertiary student (constant PPP$)',
 'Government expenditure per post-secondary non-tertiary student (constant US$)',
 'Government expenditure per post-secondary non-tertiary student (PPP$)',
 'Government expenditure per post-secondary non-tertiary student (US$)',
 'Government expenditure per post-secondary non-tertiary student as % of GDP per capita (%)',
 'Government expenditure per primary student (constant PPP$)',
 'Government expenditure per primary student (constant US$)',
 'Government expenditure per primary student (PPP$)',
 'Government expenditure per primary student (US$)',
 'Government expenditure per primary student as % of GDP per capita (%)',
 'Government expenditure per secondary student (constant PPP$)',
 'Government expenditure per secondary student (constant US$)',
 'Government expenditure per secondary student (PPP$)',
 'Government expenditure per secondary student (US$)',
 'Government expenditure per secondary student as % of GDP per capita (%)',
 'Government expenditure per tertiary student (constant PPP$)',
 'Government expenditure per tertiary student (constant US$)',
 'Government expenditure per tertiary student (PPP$)',
 'Government expenditure per tertiary student (US$)',
 'Government expenditure per tertiary student as % of GDP per capita (%)',
 'Government expenditure per upper secondary student (constant PPP$)',
 'Government expenditure per upper secondary student (constant US$)',
 'Government expenditure per upper secondary student (PPP$)',
 'Government expenditure per upper secondary student (US$)',
 'Government expenditure per upper secondary student as % of GDP per capita (%)',
 'Graduates from ISCED 5 programmes in tertiary education',
 'Graduates from ISCED 6 programmes in tertiary education',
 'Graduates from ISCED 7 programmes in tertiary education',
 'Graduates from ISCED 8 programmes in tertiary education',
 'Graduates from tertiary education',
 'Gross enrolment ratio',
 'Gross graduation ratio from first degree programmes (ISCED 6 and 7) in tertiary education',
 'Gross graduation ratio from lower secondary education',
 'Gross graduation ratio from primary education',
 'Gross intake ratio to Grade 1 of lower secondary general education',
 'Gross intake ratio to Grade 1 of primary education',
 'Gross outbound enrolment ratio',
 'Illiterate population',
 'Inbound mobility rate',
 'Internet users (per 100 people)',
 'Labor force with advanced education (% of total)',
 'Labor force with advanced education',
 'Labor force with basic education (% of total)',
 'Labor force with basic education',
 'Labor force with intermediate education (% of total)',
 'Labor force with intermediate education',
 'Labor force',
 'Literacy rate',
 'LLECE',
 'Lower secondary completion rate',
 'MICS',
 'Mortality rate',
 'Net enrolment rate',
 'Net flow of internationally mobile students (inbound - outbound)',
 'Net flow ratio of internationally mobile students (inbound - outbound)',
 'Net intake rate to Grade 1 of primary education by over-age entrants (+1 year)',
 'Net intake rate to Grade 1 of primary education by under-age entrants (-1 year)',
 'Net intake rate to Grade 1 of primary education',
 'New entrants to Grade 1 of primary education with early childhood education experience ',
 'New entrants to Grade 1 of primary education with early childhood education experience',
 'New entrants to Grade 1 of primary education',
 'Official entrance age to compulsory education (years)',
 'Official entrance age to lower secondary education (years)',
 'Official entrance age to post-secondary non-tertiary education (years)',
 'Official entrance age to pre-primary education (years)',
 'Official entrance age to primary education (years)',
 'Official entrance age to upper secondary education (years)',
 'Outbound mobility ratio',
 'Out-of-school adolescents of lower secondary school age',
 'Out-of-school children of primary school age in pre-primary education',
 'Out-of-school children of primary school age',
 'Out-of-school youth of upper secondary school age',
 'Over-age enrolment ratio in primary education',
 'PASEC',
 'Percentage of all inbound internationally mobile students in tertiary education in the host country who are female',
 'Percentage of all students in tertiary education enrolled in ISCED 5',
 'Percentage of all students in tertiary education enrolled in ISCED 6',
 'Percentage of all students in tertiary education enrolled in ISCED 7',
 'Percentage of all students in tertiary education enrolled in ISCED 8',
 'Percentage of enrolment in early childhood education programmes in private institutions (%)',
 'Percentage of enrolment in early childhood educational development programmes in private institutions (%)',
 'Percentage of enrolment in lower secondary education in private institutions (%)',
 'Percentage of enrolment in post-secondary non-tertiary education in private institutions (%)',
 'Percentage of enrolment in pre-primary education in private institutions (%)',
 'Percentage of enrolment in primary education in private institutions (%)',
 'Percentage of enrolment in secondary education in private institutions (%)',
 'Percentage of enrolment in tertiary education in private institutions (%)',
 'Percentage of enrolment in upper secondary education in private institutions (%)',
 'Percentage of female graduates from tertiary education graduating from Agriculture programmes',
 'Percentage of female graduates from tertiary education graduating from Education programmes',
 'Percentage of female graduates from tertiary education graduating from Engineering',
 'Percentage of female graduates from tertiary education graduating from Health and Welfare programmes',
 'Percentage of female graduates from tertiary education graduating from Humanities and Arts programmes',
 'Percentage of female graduates from tertiary education graduating from programmes in unspecified fields',
 'Percentage of female graduates from tertiary education graduating from Science programmes',
 'Percentage of female graduates from tertiary education graduating from Services programmes',
 'Percentage of female graduates from tertiary education graduating from Social Sciences',
 'Percentage of female students enrolled in primary education who are over-age',
 'Percentage of female students enrolled in primary education who are under-age',
 'Percentage of female students in lower secondary education enrolled in general programmes',
 'Percentage of female students in lower secondary education enrolled in vocational programmes',
 'Percentage of female students in post-secondary non-tertiary education enrolled in general programmes',
 'Percentage of female students in post-secondary non-tertiary education enrolled in vocational programmes',
 'Percentage of female students in secondary education enrolled in general programmes',
 'Percentage of female students in secondary education enrolled in vocational programmes',
 'Percentage of female students in tertiary education enrolled in Agriculture programmes',
 'Percentage of female students in tertiary education enrolled in Education programmes',
 'Percentage of female students in tertiary education enrolled in Engineering',
 'Percentage of female students in tertiary education enrolled in Health and Welfare programmes',
 'Percentage of female students in tertiary education enrolled in Humanities and Arts programmes',
 'Percentage of female students in tertiary education enrolled in ISCED 5',
 'Percentage of female students in tertiary education enrolled in ISCED 6',
 'Percentage of female students in tertiary education enrolled in ISCED 7',
 'Percentage of female students in tertiary education enrolled in ISCED 8',
 'Percentage of female students in tertiary education enrolled in programmes in unspecified fields',
 'Percentage of female students in tertiary education enrolled in Science programmes',
 'Percentage of female students in tertiary education enrolled in Services programmes',
 'Percentage of female students in tertiary education enrolled in Social Sciences',
 'Percentage of female students in upper secondary education enrolled in general programmes',
 'Percentage of female students in upper secondary education enrolled in vocational programmes',
 'Percentage of female teachers in lower secondary education who are trained',
 'Percentage of female teachers in post-secondary non-tertiary education who are trained',
 'Percentage of female teachers in pre-primary education who are trained',
 'Percentage of female teachers in primary education who are trained',
 'Percentage of female teachers in secondary education who are trained',
 'Percentage of female teachers in upper secondary education who are trained',
 'Percentage of graduates from Agriculture programmes in tertiary education who are female (%)',
 'Percentage of graduates from Education programmes in tertiary education who are female (%)',
 'Percentage of graduates from Engineering',
 'Percentage of graduates from Health and Welfare programmes in tertiary education who are female (%)',
 'Percentage of graduates from Humanities and Arts programmes in tertiary education who are female (%)',
 'Percentage of graduates from non-science and non-technology fields in tertiary education who are female (%)',
 'Percentage of graduates from programmes in unspecified fields in tertiary education who are female (%)',
 'Percentage of graduates from Science and Technology programmes in tertiary education who are female (%)',
 'Percentage of graduates from Science programmes in tertiary education who are female (%)',
 'Percentage of graduates from Services programmes in tertiary education who are female (%)',
 'Percentage of graduates from Social Sciences',
 'Percentage of graduates from tertiary education graduating from Agriculture programmes',
 'Percentage of graduates from tertiary education graduating from Education programmes',
 'Percentage of graduates from tertiary education graduating from Engineering',
 'Percentage of graduates from tertiary education graduating from Health and Welfare programmes',
 'Percentage of graduates from tertiary education graduating from Humanities and Arts programmes',
 'Percentage of graduates from tertiary education graduating from programmes in unspecified fields',
 'Percentage of graduates from tertiary education graduating from Science programmes',
 'Percentage of graduates from tertiary education graduating from Services programmes',
 'Percentage of graduates from tertiary education graduating from Social Sciences',
 'Percentage of graduates from tertiary education who are female (%)',
 'Percentage of graduates from tertiary ISCED 5 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 6 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 7 programmes who are female (%)',
 'Percentage of graduates from tertiary ISCED 8 programmes who are female (%)',
 'Percentage of male graduates from tertiary education graduating from Agriculture programmes',

## Erste Übersicht bzgl. Datenqualität und -struktur

In [11]:
short_analysis_frame(df2)

========== DataFrame Qualität ==========


Anzahl Zeilen: 886930
davon: 0 Duplikate

Anzahl Spalten: 70
davon:
    66 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
Country Name        str            0.00               242
Country Code        str            0.00               242
Indicator Name      str            0.00              3665
Indicator Code      str            0.00              3665
1970            float64           91.85             24595
...                 ...             ...               ...
2085            float64           94.20              7335
2090            float64           94.20              7150
2095            float64           94.20              7044
2100            float64           94.20              6914
Unnamed: 69     float64          100.00                 0

[70 rows x 3 columns]

## Entwicklung einer Funktion zum Auffinden für den Indikator relevanter Jahre

In [12]:
EDU_INDICATOR = "TIMSS: Mean performance on the science scale for eighth grade students, total"
DEV_INDICATOR = "GDP per capita, PPP (current international $)"
TIMSS_YEARS_LIST = ["1999", "2003", "2007", "2011", "2015", "2019", "2023"]

filter_timss = df2["Indicator Name"] == EDU_INDICATOR
df_indicator = df2[filter_timss]
records_total = df_indicator.shape[0]

col_list = df_indicator.columns

year_cols = []

for col in col_list:
    if col.isdigit():
        year_cols.append(col)

year_cols_relevant = []

for col in year_cols:
    values_count = df_indicator[col].notna().sum()
    if values_count > 0:
        year_cols_relevant.append(col)

year_cols_relevant

['1995', '1999', '2003', '2007', '2011', '2015']

In [13]:
years = find_relevant_years(df_indicator)
years

['1995', '1999', '2003', '2007', '2011', '2015']

## Extrahieren relevanter Bildungsdaten

- die internationalen Bildungsdaten werden auf den relevanten TIMSS-Score (Science) gefiltert
- danach wird nur auf Score-relevante Jahre gefiltert

In [14]:
df_base = select_dataframe("edu")

df_timss_science, df_timss_science_long = create_frames(frame_name="edu", indicator=EDU_INDICATOR, indicator_title="timss_science")

df_timss_science

,country_name,country_code,indicator_code,timss_science_data_count,1995,1999,2003,2007,2011,2015
460,Algeria,DZA,LO.TIMSS.SCI8,1,NaN,NaN,NaN,408.059523,NaN,NaN
605,Armenia,ARM,LO.TIMSS.SCI8,3,NaN,NaN,461.266680,487.960381,436.924652,NaN
671,Australia,AUS,LO.TIMSS.SCI8,6,514.000000,540.258156,527.000000,515.000000,519.000000,512.0
710,Austria,AUT,LO.TIMSS.SCI8,1,538.933284,NaN,NaN,NaN,NaN,NaN
790,Bahrain,BHR,LO.TIMSS.SCI8,4,NaN,NaN,438.000000,467.000000,452.000000,466.0
...,...,...,...,...,...,...,...,...,...,...
5979,Turkey,TUR,LO.TIMSS.SCI8,4,NaN,432.950957,NaN,454.158975,483.000000,493.0
6078,Ukraine,UKR,LO.TIMSS.SCI8,2,NaN,NaN,NaN,485.062954,500.991769,NaN
6112,United Arab Emirates,ARE,LO.TIMSS.SCI8,2,NaN,NaN,NaN,NaN,465.000000,477.0
6183,United States,USA,LO.TIMSS.SCI8,6,513.000000,515.000000,527.000000,520.000000,525.000000,530.0
6364,West Bank and Gaza,PSE,LO.TIMSS.SCI8,3,NaN,NaN,435.386769,404.126171,420.454965,NaN

## Nutzbar machen der Scoredaten
- der DataFrame wird ins Long-Format gebracht. 
- Zeilen ohne Score werden direkt als irrelevant entfernt

In [15]:
df_timss_science_long.columns = (
        df_timss_science_long.columns
        .str.replace("_", " ")
        .str.title()
    )

years = find_relevant_years(df_timss_science)

for year in years:
    df_year = df_timss_science_long[df_timss_science_long["Year"] == int(year)]
    
    fig = px.bar(
        df_year.sort_values("Timss Science Score").tail(10),
        x="Timss Science Score",
        y="Country Name",
        title=f"TIMSS Science: Top 20 Countries ({year})",
    )
    fig.show()

## Datenstruktur der zwei neu erzeugten Tabellen

In [16]:
df_edu = pd.read_csv(EDUCATION_OUTPUT, encoding="utf-8")
df_dev = pd.read_csv(DEVELOPMENT_OUTPUT, encoding="utf-8")

short_analysis_frame(df_edu)

========== DataFrame Qualität ==========


Anzahl Zeilen: 6435
davon: 0 Duplikate

Anzahl Spalten: 51
davon:
    47 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
Country Name        str            0.00               237
Country Code        str            0.00               237
Indicator Name      str            0.00                46
Indicator Code      str            0.00                46
1970            float64           91.75               525
1971            float64           77.98              1398
1972            float64           79.38              1319
1973            float64           79.16              1336
1974            float64           79.60              1311
1975            float64           79.27              1330
1976            float64           78.24              1393
1977            float64           78.45              1382
1978            float64           78.52              1377
1979            float64           78.12              1403
1980            float64           77.31              1456
1981            float64           75.65              1561
1982            float64           77.65              1432
1983            float64           77.64              1433
1984            float64           76.81              1489
1985            float64           77.19              1465
1986            float64           75.18              1590
1987            float64           77.03              1475
1988            float64           77.50              1444
1989            float64           77.02              1477
1990            float64           76.63              1501
1991            float64           75.80              1550
1992            float64           76.21              1528
1993            float64           76.05              1539
1994            float64           75.52              1572
1995            float64           73.85              1662
1996            float64           76.67              1499
1997            float64           80.56              1250
1998            float64           74.23              1653
1999            float64           54.59              2881
2000            float64           52.91              3008
2001            float64           54.41              2913
2002            float64           52.90              3014
2003            float64           50.23              3137
2004            float64           51.97              3068
2005            float64           52.54              3037
2006            float64           50.78              3150
2007            float64           48.55              3238
2008            float64           50.44              3165
2009            float64           45.11              3509
2010            float64           47.86              3334
2011            float64           43.81              3537
2012            float64           43.75              3598
2013            float64           48.90              3268
2014            float64           52.54              3023
2015            float64           68.89              1918
2016            float64           98.10               120

In [17]:
short_analysis_frame(df_dev)

========== DataFrame Qualität ==========


Anzahl Zeilen: 5955
davon: 0 Duplikate

Anzahl Spalten: 70
davon:
    66 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
Country Name        str            0.00               264
Country Code        str            0.00               264
Indicator Name      str            0.00                26
Indicator Code      str            0.00                26
1960            float64           82.67               994
...                 ...             ...               ...
2021            float64           13.79              4427
2022            float64           18.07              4280
2023            float64           23.27              4036
2024            float64           38.07              3321
2025            float64           78.96              1248

[70 rows x 3 columns]

In [18]:
df_dev

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.684742,23.795044,25.336708,23.948825,22.191237,25.728269,27.033079,26.160466,25.521582,25.566559
1,Africa Eastern and Southern,AFE,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,1186.271645,1160.378669,1219.272866,1253.36594,1275.819514,1304.206683,...,1493.119366,1493.142391,1492.186702,1480.229002,1398.577930,1422.655463,1437.091394,1428.546238,1432.508435,1449.271383
2,Africa Eastern and Southern,AFE,High-technology exports (% of manufactured exp...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.190170,5.870467,6.654846,6.890721,6.066723,5.176600,6.316269,5.704851,5.800044,NaN
3,Africa Eastern and Southern,AFE,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.680069,27.406039,28.402808,27.216015,24.292605,26.288167,29.472460,29.503507,28.305737,27.785399
4,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.300000,17.300000,19.600000,21.600000,23.500000,25.000000,26.800000,27.800000,28.800000,30.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5950,Zimbabwe,ZWE,"Prevalence of HIV, total (% of population ages...",SH.DYN.AIDS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,14.100000,13.600000,13.100000,12.500000,12.000000,11.500000,10.900000,10.300000,9.800000,NaN
5951,Zimbabwe,ZWE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,81.700000,82.000000,79.700000,81.000000,84.100000,82.400000,NaN,NaN,NaN,NaN
5952,Zimbabwe,ZWE,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.PC.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,1.821388,1.758746,1.864458,1.733276,1.596830,1.718639,1.744073,1.843543,1.850644,NaN
5953,Zimbabwe,ZWE,"Trademark applications, resident, by count",IP.TMK.RSCT,NaN,NaN,NaN,NaN,NaN,NaN,...,155.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5954,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.896000,6.350000,6.788000,7.373000,8.617000,9.540000,10.087000,9.348000,9.435000,9.293000

In [19]:
df_timss, df_timss_long = create_frames(EDU_INDICATOR, frame_name="edu", indicator_title="timss_science")
df_gdp_per_capita, df_gdp_per_capita_long = create_frames(DEV_INDICATOR, frame_name="dev", indicator_title="gdp_per_capita")

df_timss.head(10)

,country_name,country_code,indicator_code,timss_science_data_count,1995,1999,2003,2007,2011,2015
460,Algeria,DZA,LO.TIMSS.SCI8,1,NaN,NaN,NaN,408.059523,NaN,NaN
605,Armenia,ARM,LO.TIMSS.SCI8,3,NaN,NaN,461.266680,487.960381,436.924652,NaN
671,Australia,AUS,LO.TIMSS.SCI8,6,514.000000,540.258156,527.000000,515.000000,519.000000,512.0
710,Austria,AUT,LO.TIMSS.SCI8,1,538.933284,NaN,NaN,NaN,NaN,NaN
790,Bahrain,BHR,LO.TIMSS.SCI8,4,NaN,NaN,438.000000,467.000000,452.000000,466.0
1076,Bosnia and Herzegovina,BIH,LO.TIMSS.SCI8,1,NaN,NaN,NaN,465.745173,NaN,NaN
1114,Botswana,BWA,LO.TIMSS.SCI8,2,NaN,NaN,364.569248,354.534086,NaN,NaN
1233,Bulgaria,BGR,LO.TIMSS.SCI8,3,NaN,518.010990,478.843142,470.283975,NaN,NaN
1418,Canada,CAN,LO.TIMSS.SCI8,3,513.987704,533.081997,NaN,NaN,NaN,526.0
1520,Chile,CHL,LO.TIMSS.SCI8,4,NaN,420.000000,413.000000,NaN,461.000000,454.0

In [20]:
base_columns = ["Country Name", "Country Code", "Indicator Name", "Indicator Code"]
years_to_compare = ["1999", "2004", "2009", "2014", "2019", "2024"]

df_dev_years_to_compare = df_dev[base_columns + years_to_compare]

short_analysis_frame(df_dev_years_to_compare)

========== DataFrame Qualität ==========


Anzahl Zeilen: 5955
davon: 0 Duplikate

Anzahl Spalten: 10
davon:
    6 numerisch
    0 datetime
    4 string/object
    0 kategorial

               Datentyp  Fehlende Werte  Eindeutige Werte
Country Name        str            0.00               264
Country Code        str            0.00               264
Indicator Name      str            0.00                26
Indicator Code      str            0.00                26
1999            float64           35.48              3288
2004            float64           22.60              3987
2009            float64           14.64              4363
2014            float64           11.75              4495
2019            float64           11.54              4559
2024            float64           38.07              3321